apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: stalwart
  namespace: stalwart
spec:
  selector:
    matchLabels:
      app: stalwart
  replicas: 1
  template:
    metadata:
      labels:
        app: stalwart
    spec:
      containers:
        - name: stalwart
          image: docker.io/stalwartlabs/stalwart:latest
          imagePullPolicy: Always
          ports:
            # HTTP/HTTPS
            - containerPort: 8080
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            # SMTP
            - containerPort: 25
              protocol: TCP
              hostPort: 25
            - containerPort: 587
              protocol: TCP
              hostPort: 587
            - containerPort: 465
              protocol: TCP
              hostPort: 465
            # IMAP
            - containerPort: 143
              protocol: TCP
              hostPort: 143
            - containerPort: 993
              protocol: TCP
              hostPort: 993
            # POP3
            - containerPort: 110
              protocol: TCP
              hostPort: 110
            - containerPort: 995
              protocol: TCP
              hostPort: 995
            # ManageSieve
            - containerPort: 4190
              protocol: TCP
              hostPort: 4190
          volumeMounts:
            - name: stalwart-config
              mountPath: /etc/stalwart
            - name: stalwart-data
              mountPath: /var/lib/stalwart
      volumes:
        - name: stalwart-config
          persistentVolumeClaim:
            claimName: stalwart-config-pvc
        - name: stalwart-data
          persistentVolumeClaim:
            claimName: stalwart-data-pvc
