apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: secure-redirect
  namespace: stalwart
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: route
  namespace: stalwart
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`mail.noodles.quest`)
      kind: Rule
      services:
        - name: traefik-service
          namespace: stalwart
          kind: TraefikService
      middlewares:
        - name: secure-redirect
  tls:
    secretName: noodles-quest-prod-tls
