repository: ENC[AES256_GCM,data:6uOslqkJ70HntItM3YM70AKMkBslPkRyJ/21P3z4k53AD6irkCBMMayq93HcfL3CRaDz64Kljv1eu6QFPt2HnQ==,iv:NMkdS3OIgZ5pjTpFUsnKeusAPmCpwTyZmeVne+H96gQ=,tag:ThsxM0oowZaRMLRdLsaQIw==,type:str]
bucket_name: ENC[AES256_GCM,data:HZv+Lfcp2judAvSxpIV0WUGdJjwm5ICEzzuDW0k=,iv:SRa74fYSyx3sTVAOeDPOtA8smsSflSCXz7d/zvHvKlE=,tag:j9iE6hpr8MnQGpcjj4VwxA==,type:str]
restic_password: ENC[AES256_GCM,data:tiMHijxKUbUgq3qP46udh34=,iv:NgZyOQpi5tCpvT0RMXQnlIUJfdG8bC5xlAUGxgMRcFA=,tag:Lu0SAhnWU9HWsrs2oM/e6Q==,type:str]
access_key_id: ENC[AES256_GCM,data:xqjlkw86yI/Zva8ZqKKKQKcp+Ik=,iv:kFAT5DZ4b+Qup98zt0GsdqUv8ZgBW9dKsbfWbpZUOeU=,tag:8aNLBmdVx5tszuWwi5QoOw==,type:str]
secret_access_key: ENC[AES256_GCM,data:e2EQfj7Jm121MP5AZoz/hSQytKMqumDek7dRzWZcLm5SUgAP0aHQhg==,iv:ZYM1HJVY2zcmx+CzJy49+8DBIGXzlVhlHJixJKYVTEY=,tag:7dS00wbirEhoo0KDrQ9q/A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-08-05T22:31:55Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgEYXe93ptQuKCR58SKXDj2xAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsFrcT+2mq3cOf9xAAgEQgDsrOFWwzV+gWjw+/MlBm19i97kWZpXNWmqNEwqiof0GChl+gk23uMrQPyf7zHlv6ytQsPrgsOmZkcrhnQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveWlzbXBzRmsweGNxZFVQ
            T2x4dmlpTXVEdlBnRkJHV2RpcVNJQ256VEQ0CkZlRjFHN252UjZpQUptaTI5ZW1G
            SzhvSGxLYkhTYTF5NHlUaDNMc09EYjAKLS0tIGJKVk1DNVVMbzdTSDA3ZFdhZHRN
            U1JnUkFLYjlIUU1aTGNCQnU2YWNadUUKjQ7i9rcnd/kKnlcP7to3HZ7dSnvn4ItN
            vSa46mQ7udICFCQVrizyqjWKxtCWqrUbm5l4JP95HLVXdOo1xorz4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T22:31:55Z"
    mac: ENC[AES256_GCM,data:1tY2bJQBH7TDptYBNcAViUQUQhPbKugacwapxU+uo1YR4PDESWNjmJsOWLcWMCXywO85XQY9tYHETmhOE1MxT49cd0BG9s5MdMioCc8NWTRrV9zbsx2HgRK8qiqcOqII4ocPArRSctOkX7h6xXZ43sh+2ZxQz2hH7zGhvgrlbeg=,iv:6kjNdZHX0NpeN4AFySBwaFySOKtNF17Vcof0oPb9ccY=,tag:GSzrmpoGFyC0Z4ERj+5XFA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
