repository: ENC[AES256_GCM,data:WxEGijxfrGSbIqqzd9jYsbY7aH0GOqvTlIbSy/dOpY+hGOGFZqI+ozPakTPGV7910/tfTbZ4GVU1HodMPfWGHw==,iv:zgQkcXMNi+BWJRi54R/tDGc8Hgs9T65jjBgrBzEeMvU=,tag:gzjM/lyFkracfMiiGDSkDw==,type:str]
bucket_name: ENC[AES256_GCM,data:yy4sRpt8oGXStg4z6jvnLXzuIlfy8e4GEjOSrAo=,iv:TjYRvTc4Ae2wlGaCqaDJlRpABNKqpnHy5vUXLvit3Mw=,tag:GIYBuNgaemAqENOainfQVg==,type:str]
restic_password: ENC[AES256_GCM,data:KLzb1JcUgqqzUrXLraY5Fr0=,iv:Km4XKBR/WfyjRblrEgRgZqUqUh9vUwRo1w+zSzdvJAc=,tag:9JxV7CyNZp7t0b0+Wl7M9w==,type:str]
access_key_id: ENC[AES256_GCM,data:saIBj/SaftNAqhxaXhTtq/KOvJ4=,iv:TRuWp/Y/R13nsKOU7jFO1gc6s1wl/d5plo0euQml3oE=,tag:4WxQQtsM7NoV5wpPoSL1ZQ==,type:str]
secret_access_key: ENC[AES256_GCM,data:KJbNDpN/3Au8P5TdsX0m/0HT9fJDVqPRGYMEHko0uaEqQMpTQ3gZHQ==,iv:INsrmjMt/Rwfnnp9aUFmdZvURthCqkVU78pCPm5pfQE=,tag:CYWwGIbrBxRFNmdtWhLJyA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-07-18T02:47:23Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgE6XKWAHstrI4XdN89OxKWNAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDmtM0D8SiXzjAN1OAgEQgDvhO3R/Odfo18XL2+WcYqAbe71gY/Y/Ofvs88JSjOvqawDcsIJtcG2IXJtUUitXUZAuLPGi95ogdwjyZQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMVd1YW4wcm9QT0J5RHJK
            VUlma0x2TmFOSmhJNjBiOG5ocmwwV1NzWkNNClVXcEJLQlhoVmhrbXp4Nnl6QnV2
            S2gwRzBxL3dpbHMzdDRWazEyYk91MTAKLS0tIEdwNlJpQmllak1zU0crWittOHlX
            S0dlc296bHV6TldONklOeTNabkd4L28K5FdSCHrAJHx72+9gErC6fitLfxnnpYVm
            HBiCrp62f6q8LD03TmEr3yA7l21FpaSlT2vJlkD11M5iGK28YUF4mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T02:47:24Z"
    mac: ENC[AES256_GCM,data:U76FyGwQUgixKwjAXpv3z3kZGDkKQpKBYxg/skSDcJwcwBOYWT2XgeML5ltrRiWbyV+amPAdcDDYhdPP+02oACV3I50RKkBPSbtklo1sZpiuq12ZgoAc+QGS8QAflVdh6kCbcTqT1yfArmIUrbYFTtvHS7EqGCFj497Ao2MXyto=,iv:LbdxEK4CcRf8wGsAAEgKZnjFuazrdjhQ48w/gVn5UnU=,tag:aEBfpveBQuSH85EZ35FSwg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
