repository: ENC[AES256_GCM,data:xMRH/RYhLjVX5obTv/BM5lQc1EstKxhE8OyJfUCHXQxBR0q8ekhF78l+PvQvl03E7ITozH9JlYucLf922y5vWQ==,iv:0r9txlhd+KB0vZ+EVQKybmrvAmgFsl+JYAf+a1gMD24=,tag:h5xDegmXGz3o60kKi7EO4A==,type:str]
bucket_name: ENC[AES256_GCM,data:jJoECW5B4UlbeN2tD/fsw4Cx6l2rLAXx1jMZAn8=,iv:wq5XejhYhCrnW6Yuwn7MeEyTA9cmU8NlMfDEW+IRxTc=,tag:yiUI9Tpzud2oHAEOju+8uw==,type:str]
restic_password: ENC[AES256_GCM,data:uG5HxkS1Gl3c/4clII4y1fI=,iv:w0zc5z1E8paf7hemv204Ii9PNJlge5lt8O/yL4+fbTM=,tag:EUMsXb4qAN+KegZHc4RM5Q==,type:str]
access_key_id: ENC[AES256_GCM,data:vGsK5RVj1pUyN0s8IhP19kWnvZc=,iv:wJX5Gok2cPCxp40tx/TScYNOksJE4mT02qquvpU35vQ=,tag:uHJbB5X0/0Z2GqxLyUPUwA==,type:str]
secret_access_key: ENC[AES256_GCM,data:QX4Mk1ud0vGSjDocwIlc6tAtUBDCTmfiTxEiXl9VD4QwFHW+dcr00Q==,iv:oMgcS6EbQxtICwZqtbHiTF3x0lUSnysrf1lUkc852+w=,tag:UYy6Pp7gi8ktxft2OJJtXQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-09-13T23:09:17Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgH+NDh9X3tAr4JZ8uzs0xwCAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMmXGmK7IaOSfwILmRAgEQgDvihsIT2lIpJ212yz/IZeKcEuOI+ZAxnIgyFvD6ycNkQXqu8SFw4XwZr498/uWu2y4d4UvCm8dBZcikzA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eStWWGFaR0hTSldCVVNw
            czRmQlY3V2xmWXo3TncvV3U2WjduaDNCdW5nCi84SCtjcmZzYUN0bEhtV2dFSTlU
            UGRMUS9ZWmtOKzErTGl6aGNHMTNzRGsKLS0tIHZZdnpHVjJCSHU1QTkrYUlYZjhh
            Vk9WUHkyR2NaZFlDTFNYVlp4RU9NRFEKVP+E77+aY7GKRlNoqchfUdn5MKOUZwWM
            WhvDBY6HZIU7fzbYFRAZvj4prEl2KwMXWf5k1c3q8uffuswxfIJH4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T23:09:17Z"
    mac: ENC[AES256_GCM,data:MacRAuVnfVkM2NNd7hzML7NN6XeBSG80vNtoY52pg+CYi5OMUvOXf35SP6OLlHWD0Wiiu4NT7aap7XUEvDdWusdEwhWZkSMsuY/et7rxrhGN9wJ0tRZf/2sn8HKyL15QcoXPZE7I3Q37BKkm91Xr5o0DFlhMIFtYKCWyoE/do6s=,iv:Da/bEHe/WzXPr1G6jkXASOXuCMA9wYrNX0ScBghYpUw=,tag:35G7yGnfp4iWvWwpy8XE0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
