apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels: &labels
    app: pihole
  namespace: pihole
spec:
  selector:
    matchLabels: *labels
  replicas: 1
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: pihole
          image: docker.io/pihole/pihole:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 53
              protocol: TCP
              hostPort: 53
            - containerPort: 53
              protocol: UDP
              hostPort: 53
          resources:
            requests: { cpu: 50m, memory: 128Mi, ephemeral-storage: 128Mi }
            limits: { cpu: 500m, memory: 512Mi, ephemeral-storage: 1Gi }
          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: FTLCONF_webserver_port
              value: "80o"
            - name: FTLCONF_dns_listeningMode
              value: "all"
            - name: FTLCONF_webserver_api_password
              valueFrom:
                secretKeyRef:
                  name: pihole-admin
                  key: ADMIN_PASSWORD
