apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: pihole
spec:
  selector:
    app: pihole
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: traefik-service
  namespace: pihole
spec:
  weighted:
    services:
      - name: service
        namespace: pihole
        port: 80
        weight: 1
