loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2025-06-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    aws:
      s3: s3://us-west-1
      region: us-west-1
      bucketnames: foundry-log-storage-061349021976-us-west-1-an
      s3forcepathstyle: false
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: true
  storage:
    type: s3
    s3:
      region: us-west-1
      endpoint: https://s3.us-west-1.amazonaws.com/
      secretAccessKey: "${SECRET_ACCESS_KEY}"
      accessKeyId: "${ACCESS_KEY_ID}"
    bucketNames:
      chunks: foundry-log-storage-061349021976-us-west-1-an/chunks
      ruler: foundry-log-storage-061349021976-us-west-1-an/ruler
      admin: foundry-log-storage-061349021976-us-west-1-an/admin
minio:
  enabled: false
deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  extraArgs:
    - -config.expand-env=true
  extraEnv:
    - name: ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: loki-s3
          key: ACCESS_KEY_ID
    - name: SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-s3
          key: SECRET_ACCESS_KEY
# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
