kube-prometheus-stack:
  prometheus:
    service:
      additionalPorts:
        - name: pushgateway-metrics
          port: 9091
          targetPort: 9091
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: 'pushgateway'
          static_configs:
            - targets: [ 'prometheus-stack-prometheus-pushgateway.monitoring.svc.cluster.local:9091' ]

  grafana:
    enabled: true
    adminPassword: prom-operator
    envFromSecret: dex-auth
    namespaceOverride: "monitoring"
    defaultDashboardsEnabled: true

    additionalDataSources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local
        jsonData:
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: noodles

    grafana.ini:
      server:
        domain: noodles.quest
        root_url: https://noodles.quest/grafana/
        serve_from_sub_path: true
      auth.generic_oauth:
        enabled: true
        name: Dex
        allow_sign_up: true
        client_id: grafana
        client_secret: $__env{GRAFANA_CLIENT_SECRET}
        scopes: openid profile email groups
        auth_url: https://dex.noodles.quest/auth
        token_url: https://dex.noodles.quest/token
        api_url: https://dex.noodles.quest/userinfo
        role_attribute_path: contains(groups[*], 'noodles-org:admin') && 'Admin' || contains(groups[*], 'noodles-org:developer') && 'Editor' || 'None'

    sidecar:
      dashboards:
        enabled: true
        folderAnnotation: "grafana_folder"
        provider:
          foldersFromFilesStructure: true
      alerts:
        enabled: true

prometheus-pushgateway:
  serviceMonitor:
    enabled: true
    honorLabels: true