apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: enshrouded-data
  namespace: enshrouded
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: local-path
  volumeMode: Filesystem