apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus-stack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: grafana-traefik-service
  namespace: monitoring
spec:
  weighted:
    services:
      - name: grafana-service
        namespace: monitoring
        port: 80
        weight: 1
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: loki-traefik-service
  namespace: monitoring
spec:
  weighted:
    services:
      - name: loki-gateway
        namespace: monitoring
        port: 80
        weight: 1
