apiVersion: ENC[AES256_GCM,data:6yM=,iv:MhFLdTd2TBb6QPEivUDy/eEsZBVeV+Po1zworU2mQXM=,tag:40Gh1GuX3+t1F39HvGbRhg==,type:str]
kind: ENC[AES256_GCM,data:Wq/XwVlH,iv:hs4ckq5QWFYM5tfeKNmxM8XqRb7jwtvgDzM6H+BafRQ=,tag:R3fMk7T7qOWEFeBABsDlrQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4sMVbT9E69GjUNE=,iv:N8eeWdZQHwsro7uHQZtcoAKECvBZgqTi7kZNOrdQKWY=,tag:7Yov+XKq/5jkhfSOcwQ20Q==,type:str]
    namespace: ENC[AES256_GCM,data:5iuAYA==,iv:XcPVD8H1DIM4np7A2yzKoYGl3lUZtXvtnWWkPd6qmSc=,tag:S61XvmFMclFAd2H7LG4hjw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:PLAjJOcxizLJpA+26NucQRW3BzY8qlciTf6x127rixLhmkHLAt6IpNCkgFCIrTjzVSm8sqNHRnEcEdTyzFhQqwfRMIBQtnkL,iv:XZnWqOp4jvEz4omQAFGorYOTS0oEY4aquRi61dz0hmM=,tag:vpcXCfgXT14ELe6RkudCLg==,type:str]
    guildId: ENC[AES256_GCM,data:50PIoEcH2xU6GTzGH43cUC1N,iv:ZJzUyOfXc6UPlKBhVNzY46lX16cr1IwTVC9M5UEwnMo=,tag:L29eqPxyCJyPKjTOYJTBwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMUZCNXVkdzJBS2xnenpq
            MnVLUWt2S2lOTEx3akp3OFQ1bmRCVzZJYkhZCnRnTitZdTg0QnUva1dEYXRPaWND
            OHNpeU5TL1drakpRU1dOdit0UXU0eFUKLS0tIFRidEp2dWt2akc3Uk16T1B5bUNR
            dmxiTCt2Sk9BTkdlM1BIQ3ZuTVpobkkKiembT9USjZUAWaIaB2NqFTVs4idSFAmQ
            V4YrbJRS04pr8OS4Y51zLUvMGii3wRm40tUgF2Lg+Ll+TR8s748nkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:21:34Z"
    mac: ENC[AES256_GCM,data:a8W8X47wZca5cCw+bVX0DubjL8zzEy2csI83aO3TTulgqYuXgV+2bVR7Siz2eNrKyFd98nk2DxWWr6hjugylaoQB89M4FdaBayYYc9LE6tCzrSdhw2ul+MPCm1uSWuF9gVK59eU5JI6MQBLL8Tq1VUKNJLA1hJYrb3Qm17DBeyU=,iv:72RKrrUTlOykFmV5Jr8hbREwIx0lO8n/BSovJ0LAAxI=,tag:e0tdPD8nv+kMdC7s6tpP7A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
