apiVersion: v1
kind: Secret
metadata:
    name: soba-secret
    namespace: soba
stringData:
    token: ENC[AES256_GCM,data:oEzHnf+9dMXaSBXgkCPI/8foTmmQ5s4DHGO6PBBoGSD2dxzbM/tbxAgqaHUcprZBSwKGzCSU5j4qO0atxu2LEDO4NT1iYJTQ,iv:6pjjRDCD6KFnn78FqZgCPlTyAEh/7Hz7kwrvxP6cxtM=,tag:2cPvbuAC0lCXguGv4hvhwg==,type:str]
    guildId: ENC[AES256_GCM,data:bW+oVzJRmRvA743ilSiMd/0K,iv:0XyM8pejxgPi2oDza3R6988VxOULXz37BIKoCXz7xfM=,tag:ptjQ0QMhLavYfqu9fn1gBg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-08-05T19:48:20Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgElViBLT1B7aZ91//WHP2s5AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMe6chjSGg6757KBRXAgEQgDtUM3mj79rIFsEXhaH1dLSXtuOibBvoFDylhxYZHbucvRjIxzFbYmZxl4BfGNCAA5VII4EMKAVqK8B4fg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUTBWaGRVS3EyK241TGhM
            dDd5ZFI5SWtaZHJMWStJdmJJWVV0TEpxTUR3Cm9lSmwzRkROd0hwMzlYV1lQeTN6
            ZlI2RFNEeUpld3IweXBxcnZ0eDRVSWMKLS0tIHZFSURUbGxoL1p3cE5sdW5NZTIx
            T2FVZlF2ZG9VbE5Ia3lMYXE5M0NteDAKqgaEqj+EiaoCvAiavbXmoSBNMLyAuECu
            ObbqOTtOZ4Wu6hpiEsY7H8U1C/TIWsFQbpUx+ORcrb6MmfMJlg9GRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T19:48:20Z"
    mac: ENC[AES256_GCM,data:WzFcQ8+0wpzOpnp73Tr/BwskRR2/J5SIjV/iWbzcp6uRtDB5omkEMuypgvD5PdaAzix+j5+dnvrYhJM1NiwKeJhO/EYRGjag25BDbWFL+ATBFm0qq4/5zEeJrXLqV2SwdpnjEu90pCzL2PFiLl5nLIr12MrxLSboy9LI+ZNwx0Y=,iv:zywgvdznYJspJkozXhBmgXpHl+nuws8vyZamPB25bW4=,tag:GH0wKfSZMKNmKuX8G9QcjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
