apiVersion: ENC[AES256_GCM,data:maI=,iv:9Y/bqZdCYoLn0LwF4erkSb/9AMdKz0dI5ApMsm1ZW5U=,tag:yERqbcEz1n5rD1H5omU9iw==,type:str]
kind: ENC[AES256_GCM,data:LhYEDBZM,iv:A7ePd/OEOUOWHAO40gKBhm2yWO10W86M0N7O+4Diuf8=,tag:XH26JXy7eqzlUnrlQYUcrQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PFi43MMEuL4INvLuOks=,iv:duUUfUbR1GaJ9NeGqStIVFth4m2pQC4ZkZAZTE7C5KY=,tag:NodFBAMf7wHoMV6z/UDxCw==,type:str]
    namespace: ENC[AES256_GCM,data:FlmWL/C5Jw==,iv:vESQ5yAwa6BR7o69hfl7xRM6o8r3JPvSHxUpE5VtFdM=,tag:9WzbgFUo2WOc3EHk+go4PA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:XgWuKkpPyQeauQ==,iv:owJZQjYqEUhERCMcZeTLAUZjlkiNq0ivJGBRBf5Ibg0=,tag:TvrN6SyFBC0fyxYu1YvI/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSEJUMEp3bU91ZHJabHVk
            cC9RNUplTlZGampNM1FkNWJWTXdEZlY4bWswCkhGWWNvK0xUUjE3MDd1TkhpUzUw
            ay95TWpZVGdVQVRXVmMzeE9iVUtCSkEKLS0tIDRNSFFhMmQ5V1drMTdnZmJjWDRi
            S1FhUHl3aHpKbXlwS1VZWkd0b1R6MmsKCwg74fcLhzccbxwWRTHkUldnVktLJ5Qb
            8MoHA4Wk2k0+kaAiEtekeBWHOsKtuEWYbNTskfWenf71p3Kh9jtHgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T08:59:16Z"
    mac: ENC[AES256_GCM,data:+u//iFpzlfaNZGZBXwBa9IG953MZpRiIVS1KoQWFl03DCBpfW6ElTtVlJoc2D316O81AiaxODCQ6YVIObLjSTTZIUkz8ZVVYxfFeAN7oCNjwdWLFiPpdp38ZwacZVGpkXfSz0ZAvpFz/7Vof3qqOFacZLGYGULIwHaZbaAuwyLE=,iv:lDi62Ow5vektb0j9rLgYO/XKF7k4kUwIM9xu89z16n4=,tag:ex4CieEnCr5HbncHuerQMQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
