apiVersion: v1
kind: Secret
metadata:
    name: valheim-secret
    namespace: valheim
stringData:
    password: ENC[AES256_GCM,data:W7NtglejIAnKhg==,iv:y6a1Cis31f8JMFlIhEY9ZRLCtbK2mKW2ZKxofPwbsLw=,tag:OuW0O84A7HlEULSf75+QuQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-08-05T22:32:08Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgHq9LLf8xtelo5kDOsmpiCUAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlVoiAAnEJ1GKhobRAgEQgDsA4kxxUZ8/SGtcJPLuuH2nDQIVMMnJW3U3x3ooOhm47W2xRWlWGIv7uyh6D5s3um1agL5SYmtn/voWMQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQ2pCY3d0RzdoTWMybEZB
            eFBTK0pNMzJIajAwaS9ubTJJdzc5bk12MGhzCmh5b3ppK1ZpanRsVUx3cHdWSmtn
            MXgvUlgzZ0phbU5PSkpIVmFKd1AyUGMKLS0tIGsyekNLRVFmY2t6VnVUSVlIeDR5
            QWNDMzhxb2o4ZVU0L3NnSENhcDY4Q00K2TpE85nZCaf6X8ra26zqLKMO3MpGDtXO
            YEKR4095bmGPd6vQfACBKLCHqfI3enYQy7/1flH18zUzNuN6eKuMSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T22:32:08Z"
    mac: ENC[AES256_GCM,data:HEM3uY5J7nTEMXmPMjp5lezoRrJbNYfESNl2rHRJDkzrIoylAK+4JKMJkI4V4gMaPE/Vt+EtVqYrC6dAeCgjeP1TlynIUPbNCS7db8X9nD9TjYbRtycEYge4N6wnbHrmO3DhBlzYb6N5AdSFg3paHFO2Q9YL3ztOluxHAVesn64=,iv:uepfCP6fnIA3biEUga6aPpnasYo6iqzvltIdq7r0iMI=,tag:85KhjerZXn7i93i4VQKrFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
