apiVersion: v1
kind: Secret
metadata:
    name: valheim-secret
    namespace: valheim
stringData:
    password: ENC[AES256_GCM,data:h4XOk0U7f+qSHw==,iv:4g2sRKoq1Dhq7i9ofvbsFdeKBXzjWyQtZKWvSSLV55g=,tag:YWbokmQZxUGCBTiUfswX4A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-07-18T02:51:59Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgHyZDUAd8Kx9Kcn556HeoUTAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZN/OH1Wt9UCfGKXfAgEQgDuoMRpULYBv+cqqlVhGn+rWFsp6iHo/IQRHuyk8A/b6+MAracblFQwiZeQoJdsEHj/MdQSEoMaxUwYkYQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdHU5UyswYUhiMW03R0Jx
            WVBRSGpxbHdpVU53MVNWUldpMzJtSGd4d1R3CmZFaVNnMjRHWkJITnJUQVJ0TlJa
            eXBHWlhJYkRGTjN4M094OVY5VjRiRDgKLS0tIEdqNXhJMVVzeDNIRFhKLzhENDk3
            b1hadXZHMXhLcGxGeVBtaUFCMkI5ancK7axefbg/672sle7bI+WSgsMXY8iOvCXa
            v/cQxe0Fq96uw8PEX/68UifSEPgHmj8Qgln+E3VywW+2xIvZ68F4cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T02:52:00Z"
    mac: ENC[AES256_GCM,data:9cqkkBA8bfIC+NLgSyCp/hKJWFJuf0RyfmvNlfdV3ql1c/n/3zFq779HEL2eNzTQKfJdS/BgUR8Ory4wT9ZOOFwI8KFS9exnriKpWd/xadVzw8nQ5oxOv/PZ3OOweu+c5c7cVyymEP3ZUCCOdMEDGNO7+Wn20PNoZhcttjoBV/A=,iv:PiUhawV/JCcja8pCgrAjjHGIuas3DLyXwsqIcSVR9Rw=,tag:PN1+5C5tbWzYCjtNow8hUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
