apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry
  labels: &labels
    app: foundry
  namespace: foundry
spec:
  selector:
    matchLabels: *labels
  replicas: 1
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: foundry
          image: docker.io/mephalrith/foundry-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 30000
          volumeMounts:
            - mountPath: "/foundrydata"
              name: foundry-pv-storage
      volumes:
        - name: foundry-pv-storage
          persistentVolumeClaim:
            claimName: foundry-pvc