apiVersion: v1
kind: Secret
metadata:
    name: noodles-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: ENC[AES256_GCM,data:4bN4,iv:0ltS8TqKb8RwbqSX8Plz7LPalXhPUCfgJhbuusAIdIo=,tag:jbBIJa94LYcgYkU7orQoOw==,type:str]
    url: ENC[AES256_GCM,data:RZ+rh1qxb19KCfQaUVKWxvu14eK/wdlqyvVVUJZ6jtwL4nZk0Mo=,iv:wmdU832rT+wtg9u/nwUCoE74jbDV+VaVD8GzGjcdj38=,tag:yeGriFhUo/eWwUVMtrafvQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-10-06T21:27:31Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgE7JAlaKOroIo4Ez7Z4dZvoAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMKx+hSTdNZeGDniqYAgEQgDsVG0VebYth7c2xLVrHSGZjAAK+zAFDQwht+NIirE1qeYO97EkeZu0jptybdrA/9XwCGaLtHSNhAnGIdA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeE0xREJGQXhleGdIeGx2
            TEpBZEJpVlJKZWxxRWlDNitlV280Ymh3TTJJCldGRjNuWVpHeUJZZUc5RXVLOHVZ
            OTU3dzgvelZIUzdTUUlnVEZXMUFwdTQKLS0tIDNZY210bTdtZWFtcFVPZGRWcXhm
            UmgyZEtqTEd4djRIOE95UHRkS0h2N0kKQNfIl7JCePjiqipOfiJCf4nupKlbunIT
            pAl++9DrHHVh3R0EMB+WVhhGYBmmlfCc047ia8NJHCyhBg6YVRdcMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T21:27:31Z"
    mac: ENC[AES256_GCM,data:0melV6qXvSxWY2vmVGEVYgaBHH7OPAjbcWaaqMJnfHKA5LivXJgmfmeSRtUD/ea03s9te1vjmFi37elb5+KXnyXP7PV/de97V7imdx8CZvRdPnhv8ALJi6gGsU90d8uAw2nvkXeSiOG6jPxnZoT7xGrelvQeV0Ky2mypBX0o624=,iv:YqRp13dNzAgpErmRZiHT5jPadeJvSQTnconvVZvGPX8=,tag:IG+Svg1V14YPPHMSnCLWBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: dex-auth
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    #ENC[AES256_GCM,data:MI4KPpKd0q+GyHM0qhyMdRjtWFdWiWa2SwdjU0ALlzbDewheJ/vA03pDy43ElU9ngOR68H4AQxT7dMJEppWlteUZ2eiVilU6yMJhquNkwxY0/IC+skZ/fW9rTe0uXP+5n2Ol,iv:Axn+OHRX1m4QQdQoqaYS/EfuF9PwJlPLWTFGUwyR7LY=,tag:MRS/8OND8w9oaF4BLOrUxg==,type:comment]
    #ENC[AES256_GCM,data:4GbIgrgIPfrIN5rFrweYognc6hanRXNwyMUDsB3fuhbBemx5ZTfaj5ahPH8e2iXxYWHLAkwo6EgOeB3wnYKRx0zbCGtn2GqFb6cXNgG5GfeOtOxMOAXAcg/1WVNh,iv:Rrw6OLSL6F+zdV3phjmA9r3XNWQ7b/W+WpIaY5YB6yI=,tag:cy/jjvl3K6Un74jBgI+xgA==,type:comment]
    ARGOCD_CLIENT_SECRET: ENC[AES256_GCM,data:kyS6rVa8NLG5TCoHk6VQBHD8ct/IQ8RRR0MuSnisnGM=,iv:oVjKEMA47rMdNXqxuO2JutejuMACAe2/LhGlF/iT1Jw=,tag:1wZsP8sFMlWhDUQygtoBJA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-10-06T21:27:31Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgE7JAlaKOroIo4Ez7Z4dZvoAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMKx+hSTdNZeGDniqYAgEQgDsVG0VebYth7c2xLVrHSGZjAAK+zAFDQwht+NIirE1qeYO97EkeZu0jptybdrA/9XwCGaLtHSNhAnGIdA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeE0xREJGQXhleGdIeGx2
            TEpBZEJpVlJKZWxxRWlDNitlV280Ymh3TTJJCldGRjNuWVpHeUJZZUc5RXVLOHVZ
            OTU3dzgvelZIUzdTUUlnVEZXMUFwdTQKLS0tIDNZY210bTdtZWFtcFVPZGRWcXhm
            UmgyZEtqTEd4djRIOE95UHRkS0h2N0kKQNfIl7JCePjiqipOfiJCf4nupKlbunIT
            pAl++9DrHHVh3R0EMB+WVhhGYBmmlfCc047ia8NJHCyhBg6YVRdcMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T21:27:31Z"
    mac: ENC[AES256_GCM,data:0melV6qXvSxWY2vmVGEVYgaBHH7OPAjbcWaaqMJnfHKA5LivXJgmfmeSRtUD/ea03s9te1vjmFi37elb5+KXnyXP7PV/de97V7imdx8CZvRdPnhv8ALJi6gGsU90d8uAw2nvkXeSiOG6jPxnZoT7xGrelvQeV0Ky2mypBX0o624=,iv:YqRp13dNzAgpErmRZiHT5jPadeJvSQTnconvVZvGPX8=,tag:IG+Svg1V14YPPHMSnCLWBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: games-context
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:5oqsHUVs0TSfOqkSwA==,iv:pgWuF58PL0/jSDpSz2OpsN1hhtOIzWAa/kKUW0iSqN8=,tag:cm4ZoYT2FhbGgQ/XTSYlKQ==,type:str]
    server: ENC[AES256_GCM,data:6tDUAxVscwcxkRPfvjL3XoWm1R3ikua4/A==,iv:unOCWjrHB9ILlBywET3elFQYZUubn+10Wdxc1NlwPMk=,tag:QzFhpfDbJhJsrLp00N/hIQ==,type:str]
    project: ENC[AES256_GCM,data:S34Bb5EYOhu4PX365A==,iv:xfrltKabmsNOBV7EAbLzD0PF2/+D/Wxw3yJDOeX4Omo=,tag:wgNVaFv9F+9ULPYcPZ5clA==,type:str]
    config: ENC[AES256_GCM,data:NiH1NFWuekXM/qz+BPmfcP3DfRUXW3rOAk64ElpFNY6mUP52udiCy5pvREhYNjyWvN7NS9imgbG7tZvaEc2WfxEYCFn5hoRUhSkQg6aW4DxpwKivf2R80OYXKt2qTboQQ4iPNwbusuWK1Q3V0ryl5uFNblcISuCYpf87FkFVaODIlH0TW2aXWQUEd5IcRdm6Ehnobfj8Nryf2s5mdMp3sAwNlZ8wYy/SwrNyiEp3SMjqzsBWc7jkqlg/ikWou08t9toc1QzYherFBpQasHUE2tyI7Y7MjQ2p7a0+goUuLCZ//GmK8Z8YEUL7cAmUDhB/+gDTjy0faN73UlcPdwCvYbWOXJoen92b9iuPLrjxkL+OwcjpeWILp8M5721OZ4S4osf+dMu/2KEBx+ZiAm7SeLaZ0WXBaSM9AwdVd/BQ40jF+ljqvo/smzbJbEm1nOuVArYR+Y3aoyKWqeDQIR8ZHXSCkDZUX2kz4kpPrzoupKX1QscLZjf9drgDlriFaLZyAh8pFlDNpLOMqT597LvclhcwhrnGdHJFi3BtcDLPXwYmamj7XdFZs38Z1yqMufbWfsES/HR0f3nLOejmQlXveSxZ1tu9AMOxG+z/p51VG76SP8AvvgX2IpodswEICmHVZbi7kLtkveUIqLXJNmAazwrvrl77duFMAXdMPvFRTst4dW1JyzX1+0fcuRQMlBLoZ82JzkgD8gCHrypAy8DYssKVPf6l3UzZsuBjDRch+Ah5dCeHub5d3rG9MjdnmVfnhWv/eNphMzo2yX4rk/ltdhnpp0kOn+vT4HVLE8unj35sAQRjubYXOdCtcD3XZgFK13xBH7JYe6YbMdIQqONE8Z5EYXFumPj/LOea13buA2ievvWFY475RDKOhQ2GeG3xTosH22qZ2laPyCNkLbUlir3NEuM34AVVlcGbqwa2pg7zzgKIdcRxCJ9u+aCxKcM9NkQ4emQ3A8BFtWtTKeCuu16qF+NtZKG7k6NuJPtjSiC2CmeEpgd5QIYi19ZIo5k25LnOFYzGhUjE3WTATlkaj0bs8gu00oy5/Eq+iH1P/y30Ik/6emMxujHiVfnCWG8GHuYEbcVP+biwyN8L+eEGjMmSgUtksJgEoBLH2bENsTwTFpW0irXKWVZH0dQUeIR1dQZJpWtWGrAU8VKW07gnqKGvEQNK5kD8tsHCWFyYEE4c8rBasnYHzLCXbfCrBmui3wDaBtBFiqukGBcAPVKi7VXdAN+tv1zPamRvHfudNPCfU0wLZwDv7pwbhkJ8r/DwGtXfj32IErymZNVJiV34KJfbP1yXMxUrsTg8ZxVo1rPfje3rWwkTtVvGY3PE0woGUJwEuaIPl/S03ceUCnjWNDtqPvz/IVdIv36KXV8WygWvhibJoq1uIiGWKghudJJwyvOw+xOJ3ZS1LlJe0sjT//pJMKPvSBFbtfpDENGXWC/xFCKLkSgo1/J8qGALL6uxkpr1Zo0bCm0A8KQ8kJl8+1avrOUOBN+1ch4sb7pfFNCAmtReP2yhZawFCF1AF55VkD+N/A4kTZQaydd2E60vrhhc6Pol6ZxVtFvI3DV8yVLNSeH3Cf/m4P3ojK6cpwEjgzGScQOwiBH/zEuNutTOoa2mX9RCjqn77K9kufQu9kg7AYwXvoJgQrOZPF4P2kKl64/107JizamHQy5ggVGxHPcHe6khbxz5YJ4nhLsmx6SzP8csn7x0ptALfatc2oBcjXoFEc8ICAlM+9cGugZv7iszyQZcOWouquUpEB0P7jpChMXBv4c3duclX8b9748rTfcHspvatvJOXWj+6+m4blxKkKRnX1rnpHyq4eUv4tnvWyOHVBBJvMmSH9aU45LbjsCPpz/oa4lK1DUfKB4Q5cS/fwhz/HiaMxKDEU8l197lHndcqSABcr1BPnt5+pQdSdjYtUxcGnZyNOQdUk0empvqR/vwkf6PPz03Cc/3gD/OuWiIZi2hGfWN5rmS7sKrtTzqsVi7oMniUu7pPU4vB5iXgp2hxcchUkjbdkcZ04WOBuMxctl3KsLD9cWvhCEx78AvUk02/PEAVlClBg0W5A0AtiCS+nvUeBWKBaFWL60JpCGVe/QwbpMMCOdcFSAt4h4R/8xsgS685QU30Se3JVtH2/5VkrT1CyKbR0FI6oH9e42EKsjRtTBfm0oMVz0NQ5wrYDdEmUJNCKBJ0YzohtwLpnNuQ+MGRH8XwKiV5orhhNSJLo94H+e9NqcugnKjrlBoP9pFGHyl2PE0t7wkm4yF2Hi/nIZI69BPv3x/L7MOwj5bm+5WR5I9rkB6du6WSl/cH3q/R0cp2O+wDf9GC4q26XTzQtlRYFA2sCg54j/1+mw/MROOXvm6IKJxSawvxlXMmzq0JmNhwQQB5Ah6Us3IrjoH2I7KdbQaRPhELsTeTyIIAe95gpmGAPC+V6/Bwh0HKVJDR3UFqHhovT98SN67thy6JO1myGtTs9tgNxT1VbLNnkk44LeYYH+JSCYqrQWl+vWK+GNv3KQDLNoYznXVzXQxd565uNC1mTWLks8WmpxI6z+olyr6nIMJxeewC8JP4Chp7TNdbX0reaoMZQdTXou+chJVHXGSEFgWYFBzr3/PQqCLK+XS6uGWNPgofQEbS1IyQHp9rSDTh8uA3y+K09TAFQv1QTx+eBaQ3+C3BnVCQ5iu2Gj/589ToyzDZJKSHJOKbqQmerOFXOqkEvFFCUrTP0IsVC4udu/fsDS+NSZMxHBYbHJmnG5ltS4gu4Au1D6FAAz4ub/yH7NCcHRTR+stSAQBbGDilmuAUrnPCgmxIMwlYlNPnmvwVUrXAQywPYsMQ2Jpa4oKfThUeB2nKD6oPgrNDI4ZYvJMU0xcahP1+OAosDRpgJ2SENxfbB5W/Revmux7VejoBPITs+caVeORznS7WURqqjEAx3APbOzJ61mfqQL6Hld40uGoQJ48iPagsSTERbi8P61v0sjz9jFgNYYpEdWlkn3LVXjaDDVIraT19sNIHay7e2Ao8dCMtU0CwVvJgExT2joMowuCV5SVyFTJicfGMELm0sOiSZRwPz6YrHKEmudSEqB79Zl3mqY0D3xzEeVWhq1InR1/Kr57Nk9MLiT81gwI1b0JcO2mIzZWF4EtXJx0MOIauF9T9S319XQxgMngjPIaXPQ0+1nI7PLMDev+IoPQml90oehAIlWXwhgxEDXr1K1rWonlKUrSLYh9cUYAfPIzBgDSTfDzwtcTLQMn+pFTxUnYLRXn6xUKF24sTmMxRTOYwNDxixQNe6WwwjZV9cSc+IMJfdtGz/9+JT1he7DiL22XPmASYeXuHjLJgx00+XS8f3za6tZiq8e4vuuDO23HK1Z99IGhv+qVD3fXPKMZ3LOiVehdv0N6W4YAW3WV0DsWUZvRsOMeEODaqaGR+9zVmTRf8Y/rd8VDSBS3cBCnDQw6TCB5F6pYa8P0gsdhz2Mwzamqg6TPLbJ9KeFijLO+MXIqhgsyglwRmxFE5VmYdPxQYvrRw3lSDPJOg2/0v4WvGtPHbHBQkhMhW948/GohAava+H/HJruty6lsw4N6Ur3sd1yzgHv65nF0bPTDZb2Ur7+XfVc2jM9kB7nzJ7oclOmiAD6Dk4EJxr4cueHUdULM1B8aZ6zTbfvhDL+O,iv:idM2DfwMdqavdzgNgyyvXBBo+JhklL5O6G8WY3PtCac=,tag:JSh1tkcDMlAzQcShPwluBQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-10-06T21:27:31Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgE7JAlaKOroIo4Ez7Z4dZvoAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMKx+hSTdNZeGDniqYAgEQgDsVG0VebYth7c2xLVrHSGZjAAK+zAFDQwht+NIirE1qeYO97EkeZu0jptybdrA/9XwCGaLtHSNhAnGIdA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeE0xREJGQXhleGdIeGx2
            TEpBZEJpVlJKZWxxRWlDNitlV280Ymh3TTJJCldGRjNuWVpHeUJZZUc5RXVLOHVZ
            OTU3dzgvelZIUzdTUUlnVEZXMUFwdTQKLS0tIDNZY210bTdtZWFtcFVPZGRWcXhm
            UmgyZEtqTEd4djRIOE95UHRkS0h2N0kKQNfIl7JCePjiqipOfiJCf4nupKlbunIT
            pAl++9DrHHVh3R0EMB+WVhhGYBmmlfCc047ia8NJHCyhBg6YVRdcMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T21:27:31Z"
    mac: ENC[AES256_GCM,data:0melV6qXvSxWY2vmVGEVYgaBHH7OPAjbcWaaqMJnfHKA5LivXJgmfmeSRtUD/ea03s9te1vjmFi37elb5+KXnyXP7PV/de97V7imdx8CZvRdPnhv8ALJi6gGsU90d8uAw2nvkXeSiOG6jPxnZoT7xGrelvQeV0Ky2mypBX0o624=,iv:YqRp13dNzAgpErmRZiHT5jPadeJvSQTnconvVZvGPX8=,tag:IG+Svg1V14YPPHMSnCLWBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
