apiVersion: v1
kind: Secret
metadata:
    name: noodles-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: ENC[AES256_GCM,data:PJEn,iv:xHgWRHkwwga1gydoyyhYWnZGP2sL5zzHe6+Zw4/GK+Q=,tag:gBA1zyy33fC+txYfgphLOA==,type:str]
    url: ENC[AES256_GCM,data:JucdmnqBZplnC/RF5OaJ1m5oVodqEkjLDsD72dOjfwcgPEgBZT0=,iv:vKuCTu8aQUxkvnnRsoqK66m9FBlel1w29x+51BXEtvM=,tag:MzCGBqu6Tfbk+kfyuoWH2A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-07-07T00:07:34Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgHu58+sceZ4Q/UsU4BAHoDeAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6lZucNWDP3hSSii+AgEQgDv6PpitKGVv7k/AaCK1BIna/IxWKuOxLI2Y79QRWTp/EfKG5Mkswcb1oEt0ovBqXd8n9q9QYpyG5Eh4eA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYUJGb1QwUkl2bElkWXRO
            amJVTDZJZzBadlAvTGpYSU9maThPMzNMY0JrCnFVeHUwdnBXUUxKLy93UFFxNmJ3
            ckV2ZDNHOTEwR3BLc1MxN1RaU2tGbk0KLS0tIGc5RGRSTU54LytYNGx2NkNQcUhi
            UE9iSkRoVlU1eFYxTUtBRjRzVmRxTU0KsWZ4mXKFXeHyI4Pc/li3gggTBU5cBE9W
            AHgyOQGjr7vWIlENidTwPqflbu/d3dookfA3/7JEOdEvP71Vc63yow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T00:07:34Z"
    mac: ENC[AES256_GCM,data:yemjMvHaHVyllpgz6Ac4OmGmxWOeJnJMGmNyWM/Lo/e+6BTd24Q2Pzf8EqAqLbtaw8J/6qVlwVvXdvj/tjYAkmsHwyBWxITbRCZ2DPAh7XFHWFNoyB/4bOtg1A90frNzIh1dCLnNFQkHhLQJ6Au4jwfHPWrFWIXyEqHdvLU8itU=,iv:4tcfWufaqbUjqjaiMTmbLr/bnyG0a6bJ6cFbri7c/+0=,tag:WSVK0UDr7B8H61ekIwVmvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: dex-auth
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    #ENC[AES256_GCM,data:TSIp9KtUjTSCj+mF5MS4lStWhSxRnNPwHKE7+2aK1Mm78CMDUy6PYFyUVKHH3x3tOiYM9FWUIiG5cbt0GXetd/DPgREc9SiPlAqKeOyZpKcNDh7qKfUkbHQt4Sj2BDP2RPiF,iv:elhw0TM/u177fte0Z2rmuMeAk2sMoo/0fEjjbnSB9G0=,tag:ubleTGABH8iHQCug+QEh4w==,type:comment]
    #ENC[AES256_GCM,data:0rpg7MYdvj2HM5J0pFp7Oot7ZEeXLmOL/6vWDv6rrDYhTej0TfusK0aWuly7Wdg9JaodWa/j/wSy/OXv+tHTNv1ilJKE2zFfAZm+gFkolPQXOoCrtXgkCU9qWPhn,iv:1jYRNU2x4RBW7zQH8V78r+9jO3hesImOeLLlzIpTI0k=,tag:ydCDRqDoihgsKL7wJFJjjw==,type:comment]
    ARGOCD_CLIENT_SECRET: ENC[AES256_GCM,data:Fan7jqHy6M1P3irMe6HjIo2qmZQYiGn4454etwVx1Bo=,iv:4jvHvMYcjBlY/ED+BMvJPzA3kHQv+wbF0CedlvHBews=,tag:FpetR1GghkbXPrbQ7xqUNA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-07-07T00:07:34Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgHu58+sceZ4Q/UsU4BAHoDeAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6lZucNWDP3hSSii+AgEQgDv6PpitKGVv7k/AaCK1BIna/IxWKuOxLI2Y79QRWTp/EfKG5Mkswcb1oEt0ovBqXd8n9q9QYpyG5Eh4eA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYUJGb1QwUkl2bElkWXRO
            amJVTDZJZzBadlAvTGpYSU9maThPMzNMY0JrCnFVeHUwdnBXUUxKLy93UFFxNmJ3
            ckV2ZDNHOTEwR3BLc1MxN1RaU2tGbk0KLS0tIGc5RGRSTU54LytYNGx2NkNQcUhi
            UE9iSkRoVlU1eFYxTUtBRjRzVmRxTU0KsWZ4mXKFXeHyI4Pc/li3gggTBU5cBE9W
            AHgyOQGjr7vWIlENidTwPqflbu/d3dookfA3/7JEOdEvP71Vc63yow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T00:07:34Z"
    mac: ENC[AES256_GCM,data:yemjMvHaHVyllpgz6Ac4OmGmxWOeJnJMGmNyWM/Lo/e+6BTd24Q2Pzf8EqAqLbtaw8J/6qVlwVvXdvj/tjYAkmsHwyBWxITbRCZ2DPAh7XFHWFNoyB/4bOtg1A90frNzIh1dCLnNFQkHhLQJ6Au4jwfHPWrFWIXyEqHdvLU8itU=,iv:4tcfWufaqbUjqjaiMTmbLr/bnyG0a6bJ6cFbri7c/+0=,tag:WSVK0UDr7B8H61ekIwVmvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: games-context
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:lg9Pj99holzKEaQGzw==,iv:N+nPBIwnt/SK8VC2c/Ryl/eE5/IA7laqEWx/lIvj5PI=,tag:khsmSWqPcDBmCSe/WKKkEw==,type:str]
    server: ENC[AES256_GCM,data:SzzvL1S3nELQItsuIPfbJvoLntp2YEN6Vg==,iv:VsuuIieovS43COZ1vw/5lfaj4HFQ4YHQ0J/gueuqBH0=,tag:3dWz44mHXllXIYeH8AJaIQ==,type:str]
    project: ENC[AES256_GCM,data:xRO1n2oon9Kl6mxHxA==,iv:JEgeE4ahKjjIXgwM4xYdE2UaAC8tsQoFjpfsxVaB7ns=,tag:Mrb8ulh1E/Ocm+frC7JjBg==,type:str]
    config: ENC[AES256_GCM,data:j0eivbGRwD61A+bNH1YQYQ5A7F0ssEYHi7umZfBXyl3UNIAJKbodiQ+36pd9szMlGTWsRSr/mevNu38rNcI4YlklsgfyhidXF0ZjmXDjyrG5mqxQiGwwyiD0ZscN3uBnrQWtGT+TsVr1te2kKDbwaou+THUTxzKfklquU3/TGerPzxgqMlMpDmneHqLSe9SxVl/0eA+R/3wrwdXrugajcAGNcYSjSwBrdIAVB6Yoxt+HYgmY0LqKf6okXiYRDpxqmPQ0HDvtchRYF40HorNoWrJPxRmyFGsniaAVgihoPUzaVwTVPVDLS6GH2yvldo0Qmr10JCkPXT2eV2y9muOgm1/t0FI9AJICIZBMlGMRAPwzaclL68FsNThT5+xOTSjCEPa/Lagijzxz7VlZ/86hoDbzDAUVmkAMrRsWG2x6RPeg2QZldtNXw6amCClGc2ItibcW/QJadW6BXtl4z9hlM1eZ5s2mxc/w2EDaMDVCsif+LWS2oDfwIKjz/DU4wZzPRHrZAWGLCn9DKta8de098f0PYyfkds1uDMBNedx/BIY8rYT7Vx7RiULEPOUkM2Ip96CQ23pJVNrpzbmNnnIRwhA9+9SURFohlsNURbYTQlIxZQlk0ji7G4yIvPBkFK/nu6T+f6Uwm6qzoep4MtiXIzNnjgxWsl9AB5GlSKysPvenKo+d8USySX4cSjScmsPNr5/h8F2s/cip9bR06eHLUla92bRWTq8s88Xr5x5Ho0arUI82Z2oHawJ89fZ2/z08WsmJXtxRzvZgqAaHYurOGi2cvCE8HJhlBZVBYIb6SOU9hnvTT/AC9B9XfnSRIi0NbhexMJ7jevGUnPGeiwcor9Mjs4wjUojjjsryPpv5YPddtBvqHXxxai1tjEhptwvB8BqVANLKDHu6HcUS87BKCNUih6KdUZiwWYOWFojNQb8uF2+JWCV5gQf56R1sIhxRMnnzsqR15rsLgxRjG+8N0/fSVh4H4Uuu4/+ACg9TMi8NlPT9gA1fbjX58PPAjGIGesEvWE5sjKvRTaK3DWWoOYcMxlqKyVaxBgSKP5AiTSFPyODjZIt4sh32wcrjjUoNWO859OE+nTPDNSx3EOBMwAxMlL4mhdmA0ou8k8Q2yEnonHIMU/DlF1U8CvfOsMKbOeuTYFtlONY+A9YTY+BCWcfHp2h6JkvsVtez5wD2Z2egvXT3BN9f5obRIpwf3ygFc2aD1L5G+n0CTvq3SIQI/Oac2PKPCp0vsMAufgyh09JdP/WuGOSFTIoE8Hi/k79knY+zGEP4mP74xDLOsDliZzU7vu9GVjygZV+22IieEqRpaVVdmH2Yg/xGKWBNs2ChdfOiqrtH0jdp6FOARwg7ciOw2oXa5SIu/g2lhISHubgixEsnI9xglvKxIHoXMqKc3uicV3yd4AdJL4OoNVPxXw1vaAcwWP7Otr70zZxtwIl6oMFy+IYNrMSL9LWtfGxTd5d55v03g0EIJFi3XYlybzq1d5XubkDUzGn9tOGBhKYORGxLpvZ8Y3BaNeMj1QSol0h7LdsnoAshzM9TYZYTTvnuzqDON2Vo6q28txImr0PQ/37vdo4BJ/DmsJCR25tmvnXMoBILWgycJu7bUkQcMU+PsYRt0VRDVQvjAdslpjjklvTpkcCNFQcmbhsFi632xxMi1lrtYQJS72dWET3deIxTq0KwBpSeijG4VKIdPLGmD9lnD9bit7+rjUYhLC63XP/6YICdl6DG5n1RJ7JquPGuW6OiCXKmMB7xvyOtkHCGRL3eLmD6H2bEyn7f4kS3N2FQyjfG4bMJdLOTttR/6i4wrhCi81Irb/YPT4wAbRShTXpSHljKw54S49c2i/nf3pfjANRnHjrmhQMY6IGcOpTg7tGQ9eFNqlfoG528JRiTGdFvfUdJvvb0ysiUtjaI3M8pRmgsQvXcqCZ0QhLbw/EKhanXdwwIwoHW3GDz9vI8j3mQjVW5JSS8KZS686St6PdYK6Z6tCe4x22AVoudF6ZFESQtEXeXqp4Pq3fIS8jKww2IblhJ4MsidTujEXdRBlUOgKhR4K0k/pHhKw/DEylfwEaJJON6RZktCZqRDZ3beG/To9EQ4sSjtsEMRqI7PZENsMl0WGYuBkwmqWLFCnC3BbEa3N/zMItoDj1y08y8DwZH+dTwXg/ORarbR+HyEiYHvUl+x/0uWqrxHpm6luxGJJiOoXmq96GS+vgWDW/dHjSDp9YvttFyEPSe9toMbtQz2ZvgYRHqM10LQrN2Ui4tp7QUCA5Rd0P4vAVsORWGxPcydbgCvVjWOlcXqDLcqubK6n1eyJ2Hj4TBHaAKU2nc5NcushYqCUDHakuePSBbtoRL2y5/O3f7P/kCGB4cpXgvqT/hNFmQTG0NwNtIWi4jwHnRLIih0eemRKA+vdjkYhN+TOdZe56q7jnw+0I5MLrdn3uKoFP8/e49MArHb6g3cfpKekC2XcZkFqien2+G490zvJy8P4Rk3lpIDzIehlQIbkAA1kB3jHXKyvFDdox/8rAM4JOnE0YT2D78hgTx67uILhUljShGyDKmzKnsouOapl28yqBRbZt3WadEDL+NsWOwJFNvtf+W/na8XDe3cneHw1PuB51N1/D62Ytm4dXFxfXrY1vm+8eG9bmOmvWAULmxV/PlEn2ha2d5gJDkrVxn2cnwdrJiB7bO3Movrl6Mxy3MSFH2SQCHr/AVWCTVQ78T4f6CxX+15NkBqM2rrIhGuIcUb3HAkn7cF4mfeL09SxbN7zsL0SD9jJ7+BghYSvxZNiBCUH2t954d93agW5y3SVGzZZPOdmq80ySwd8srG8ii43ivGkCHa5JVkYlMMJNi4/ne6In32eFj6CYrXchteXss6syfFS55NKQ4Y6eVKaTXFRI65GqnFb2IQUc93cNVnp4x0+TcZbnIihFRoN+/06xw0FWxXDnpKD3YGn5yYLWbvGIJRQm4waXsO1R83FOWxuPVeSPWx0PO+dyOYXeSeZhEAajsx5u/kAtr9bDSLwi4RYOMuTn5kqFNVR/z7VUXkcoSMfwBlfRWm2eNbiap3GNlO5O1An2mhtPNb4G6QLW9r3eNQak3bBtx68z9tXQIOECGNUDWxTjGQRVu7MQw6FnD7Oqx07pCbYaob5RVMavNQSaL5wUwhYiEp70rdyJsIXxL110J2eq+/PVe5mHOrrPpZeUiCvDBDkXK+7zgf3Xz+fSsk0/QSRWASayjrt27YNbB5d6NqSf9EUhjinpYUCWMZfk1ThdFcndyyXWiEC6ciivkc16GHJ6NMeFkUvaQBaLCLhg22UlLNIZTZFGj7JIpothGRLmhkFKNxXWTiqpErAg9Y2jJZ+c8+9Jk2dIvIwLfKDI5+hKBrfCQV2sdd4Yf79cO4BOxnJC+Az3k9v2/9sZMfpiwDJSSImxDjaiXpF17UBXhKSqGm30VtespPXGudzPEnOkPXH9L7L9qmEwG1Y9dh37OV9X7qDMZFPm5ixLRW2qt/iQlDxI7YRrRAEnKlzZ51kaXG14kvZBY2ZKZycQT0arjGA4/pAWhAeX/k8oaJFDK2wBrl6Fyp6Ts8+3tyDMrsFlKrFcPukfQ4VQ3bInSpHVWt8xetTb8OTEwtZC9kQ6F0cGqgmy+cQ542WtyzRLxeqpe,iv:hEyApmoQhNHgOujii5MlDTi928u6LaCl5ladfYAn0Tg=,tag:6RaMP8URHDTMG1Ic3TnOlQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-07-07T00:07:34Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgHu58+sceZ4Q/UsU4BAHoDeAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6lZucNWDP3hSSii+AgEQgDv6PpitKGVv7k/AaCK1BIna/IxWKuOxLI2Y79QRWTp/EfKG5Mkswcb1oEt0ovBqXd8n9q9QYpyG5Eh4eA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYUJGb1QwUkl2bElkWXRO
            amJVTDZJZzBadlAvTGpYSU9maThPMzNMY0JrCnFVeHUwdnBXUUxKLy93UFFxNmJ3
            ckV2ZDNHOTEwR3BLc1MxN1RaU2tGbk0KLS0tIGc5RGRSTU54LytYNGx2NkNQcUhi
            UE9iSkRoVlU1eFYxTUtBRjRzVmRxTU0KsWZ4mXKFXeHyI4Pc/li3gggTBU5cBE9W
            AHgyOQGjr7vWIlENidTwPqflbu/d3dookfA3/7JEOdEvP71Vc63yow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T00:07:34Z"
    mac: ENC[AES256_GCM,data:yemjMvHaHVyllpgz6Ac4OmGmxWOeJnJMGmNyWM/Lo/e+6BTd24Q2Pzf8EqAqLbtaw8J/6qVlwVvXdvj/tjYAkmsHwyBWxITbRCZ2DPAh7XFHWFNoyB/4bOtg1A90frNzIh1dCLnNFQkHhLQJ6Au4jwfHPWrFWIXyEqHdvLU8itU=,iv:4tcfWufaqbUjqjaiMTmbLr/bnyG0a6bJ6cFbri7c/+0=,tag:WSVK0UDr7B8H61ekIwVmvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
