apiVersion: v1
kind: Secret
metadata:
    name: noodles-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: ENC[AES256_GCM,data:l5k6,iv:gs4vTXyuiU3/A5WgnyIt6WHu/MaXCsnxYwINZYi7saE=,tag:w7bsVpw+FH++2A9g2BAJvg==,type:str]
    url: ENC[AES256_GCM,data:cx+EFhbp6O/AkR5+dj4I67v38n1rrpKbMVWudYTJ3Imy9kzLwyU=,iv:qOS2Ao4P61LqVKd1t1G+njHDW5arOc3dvUhjC3khkj4=,tag:geDJb3494IrTLI4c/FP5BA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-07-18T01:04:58Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgFJzsRjqu2WSpkbn2G0tk4jAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2rqJKbn6kWaL0aIVAgEQgDutUWwP3WamfNI49AAvDXg8b6FAs6qBwCJDFVdJzrujncR9Cee3YsF25exnS8XoV4k8gqStvgoobV89RA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbFFtNlVPcklRNG1UenE3
            WlhYekl2TzFXM2RCTC9XbkpMQmlZY2NNbjBZCjF0RlBDTm9Rb05nQXByeGxPY0FF
            L05vTTVKMDNRZ0o0cUdORWdHWnZHZ3cKLS0tIGoxNXNEb2dabkpVcTcrSkVXTXlw
            WDFWelJRQWZlWVVsY3ZreFNtTis0MWMK83h6O9oMMCV6zHF5FVzVK6mYDEA8GgB/
            8sl94woZw3DsJO+vtTFPivHlsR+lFLnFPu5+qXTt2lT8YC6v6h7FMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T01:04:59Z"
    mac: ENC[AES256_GCM,data:GclgRgVdCQ6zlcR2p7UPGNDitR8SW4Z6KtuLNE/tC6SSq/+kAsFqoOjA1JjOGAWsUdtTMFY4Thxi91xgcXk9LNW2Ev63705him2ch8DhM80Pg1TSY4xtH2gVtcxu5UWGz6skgcQjOBTWT98OYRbOvD4+PeObkh7UcsCjdUI6CMo=,iv:sZf/oR6mB7EqU+J/wWhwEitAWN5S7FfPM3GbfMwvBOI=,tag:sLnGSJuZMmxvvrZ6ebZ5YA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: dex-auth
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
    #ENC[AES256_GCM,data:F97F2w6ueSNXlP2SEvb6+P7wT9aYqr6/XpmKX8QFp6l8R1vV71VW1rzbArOeqtL2YD8LQlzoZWp47Kno2xJIuwmCJ/peadNtKy2tuxFrj5qGoiiKzyQIMhUMABHQbmfzLZWX,iv:cp6dbq3tV8RwVMHzkzvKKYxBPJuRzn7DTfWsVPQez0o=,tag:vNkaCbujSAAAv4h0JUQUXg==,type:comment]
    #ENC[AES256_GCM,data:6OsJRvI9auJEVm1EUDI3nhnxuAVE9t7p/0sCMCH7rBy6qFbmo2hRUi3dGLh9w7gxpuHs/elUvQKr9koAD0R2KrEEcZPTnNjyaD3Lprky6hZDjsjSTMOs/EnAOmOZ,iv:ZmUFK3dMuSyYL3YyAtadP9pnq1MtEhb3sHvx+PM4yMQ=,tag:q/r8IDZ/4uzGRPcOppNqlw==,type:comment]
    ARGOCD_CLIENT_SECRET: ENC[AES256_GCM,data:KMKCQn70GybgRR4jSkSbRmES67uA6P/Gtv61kTAc3QU=,iv:WyWQQYvPeEmxYqx+1u2RrnMvHGWGFQOv3mOqOqT7fVY=,tag:95iKLkUlz/evolp4TwPmAg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-07-18T01:04:58Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgFJzsRjqu2WSpkbn2G0tk4jAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2rqJKbn6kWaL0aIVAgEQgDutUWwP3WamfNI49AAvDXg8b6FAs6qBwCJDFVdJzrujncR9Cee3YsF25exnS8XoV4k8gqStvgoobV89RA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbFFtNlVPcklRNG1UenE3
            WlhYekl2TzFXM2RCTC9XbkpMQmlZY2NNbjBZCjF0RlBDTm9Rb05nQXByeGxPY0FF
            L05vTTVKMDNRZ0o0cUdORWdHWnZHZ3cKLS0tIGoxNXNEb2dabkpVcTcrSkVXTXlw
            WDFWelJRQWZlWVVsY3ZreFNtTis0MWMK83h6O9oMMCV6zHF5FVzVK6mYDEA8GgB/
            8sl94woZw3DsJO+vtTFPivHlsR+lFLnFPu5+qXTt2lT8YC6v6h7FMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T01:04:59Z"
    mac: ENC[AES256_GCM,data:GclgRgVdCQ6zlcR2p7UPGNDitR8SW4Z6KtuLNE/tC6SSq/+kAsFqoOjA1JjOGAWsUdtTMFY4Thxi91xgcXk9LNW2Ev63705him2ch8DhM80Pg1TSY4xtH2gVtcxu5UWGz6skgcQjOBTWT98OYRbOvD4+PeObkh7UcsCjdUI6CMo=,iv:sZf/oR6mB7EqU+J/wWhwEitAWN5S7FfPM3GbfMwvBOI=,tag:sLnGSJuZMmxvvrZ6ebZ5YA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: games-context
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:89xnXmQKEKT8lm59gg==,iv:MtuoHVIkDgNIcVdHC16TFiY/f7v5BtlRG4jKYDIax3k=,tag:B2bO8L3vLLTjJCm8SYewiA==,type:str]
    server: ENC[AES256_GCM,data:A268EsHJIGke96LO3WUndbZ+MVpk0WQXfg==,iv:FjtOldfWoPu3fAE3/AlX5xC61cZJ1zs3WjENQD9cra4=,tag:SdMQXeaBVuw0ESQES+UNbg==,type:str]
    project: ENC[AES256_GCM,data:0MORWeFO3ISj2z3PZw==,iv:gVOqWkpXllCPFM6Zfj5Gzg+qLXO/TkzMliVa9C17roo=,tag:VyhzWNa1rY9qHT7Y0HMw+g==,type:str]
    config: ENC[AES256_GCM,data:HdCX3CZyB3N2oKvDlSAn931lZTjgkEgA7s8PDO03XSPjglsO0h7uifaT62Dm403DVnsF+UDo+Jglb0QwIY7SIBPAdU1VWnpoJCM3MELM6YytzEt1RKJIQwyj6dUaFNwhudq/8a93PaNu/v4mDTFFKJqqlwkqf+Mui494BPUcAvu0Mf02+VAxibThWM/K61uo1YciSEkUUs0ag9R9glFpibYfdZG9ZzWp1BsCtIm65EFP3XVB7uwLe6cZWU1IZZrISVOhn0GEXur1UGlHRWYyu6ZrImzzODT/NFiFE7VSXDmrBcbyn6TfjJsTvOGt+j01Admf1tgBt7iLnt9SGLY946MTfb/+aSjqQo+cvNirYR1kVB+c6E13ICq60l2QvuD1ytRGM70Xx2HWeBfWO+OHImANayf7qiRDS4R5B5PRspDrZXPUAPw//hcn13eOTWJRhZDRgVxjs9dAoKebfCHJNb6DwCZ4TxoNPpk9rQaOx3zFbD6Ry//9+ofSyrOS5+b7rzDLgsnX1N+Z5rKpW4uTiDXknKlwxXcKDom8swkstBavgJu/CEopmoMqJMjHesEz2FsTvOLtDLPWxjvDU3JkUkkB8z3QQ26WuHnsp/mbVKoGnHHR55Swa8e5/P1D/HwLgr6R5QKHIxzHIy+CYRKKQ/bTcO1wD31Ln3Pv0QSgGLxPGSrVP6RxV6xgxvATR2nbkufuoc3lDEaTnUXVWkL/a+YpRqYZdfI23oBsZf0IgIsVGdOF9K1WwwC+fJjEI6+L5zkTYaQrx/Y/amrqzKEfpAMElgIHTttaSvfWWI/+0VF7a1Z0x6B8AUQz48ePJWh2UT0ZtBuQ5Ne72HgnBDt6SFUMuqDpXjfiZlNI4dVkyjesRW7YzERZU+c4VkvpYeVnhGtoNO8fT469iLhz0GNV1urRZ/1Su6wa7+GLcwtsZoBFpwDVPjeMTdnGt60+XWgLYe5uXZEwXSvmldNBfj6UqT35H8gYCH67AmBqDUjmojRmWv+gZ/kov3VehRVdDzM4UgKbLJ/ZqIPLXO4C9EDgaC0p+0BbbKnObpC5EtD0OJqAx3bwuKEyU5OHGR92TNEKQL2w4uVzYnvQ18Y4NzwZ8C5Zu/D/ZmscyXs47kOyBCZNYq66710dtGfe6gbAdtxZSC4mh9kDLjWNdkTU/+G6U7F6Dmr3w2Od/UtCHz/jtkBUGCrMCAoj+RAFRYBOvl0Jtxjq/g2a079482WfYZP5xCZtoZPSrV92pMyKNxgOths0QoxNUmKWOSTfMYHl1TkZsXC55froMY4uh+2EcF/wSNvwIYfOFRQP8WpNHM/bHSeM4xQxAGxr1YGTZLzDRJGFKA+VrIK00GASOAzazXqdRw7gidtZvJ1wDR+1pqkRGgL7/W6xKxR1egKdXgUFZbPumDsX99uuGQ8eE83U7wB71mYrFnx85TOIU/I4XaxESWGmR8SZkFG/es5EZ+uv0oAk49U8z3EatzHZWD80r/R7e1rLrahdw3p7uu572GhgmF7EsU1ZXZM+pmny9jLiEH987FpHckm+rCDMGRlhrQSY4ckZut4bj5Sn3LRj37Vp0xZWdsQWeQEaWW6Vv+QbXX1VWdqGS0UBN/vIId28xmf422KqXEuunozllcSUvktJyE6WfkqKiAcBXGpQWs2EBuOXK3yw189nlroO62XCtqo9pbq5FfLHapUe4xD4P2LRCNvG5V5Kw2b2wkn21tWPnRUWeJId5jNah0qW//YOeH53P24Sd7q7yAnISgsBi1mEbsUeHQ0TAKcWJcjZLhDDlHJn87HDNzY9Y6UuiTZZ+GW8J2/XD3m5ku7kgJi67WfgeJQmI/h1U0fMk7VlBapUZWdorKyoE6qBPpDsMTt2XaYcRRqq5RFa4xTAdbC40DjUSq2Fx99jX4BnDvuy9c/tTRIh/SYtgRYivatrQDId2iEAoiFIQDJIOvjuk+7oRv/VLzs8S+kHRCvvYPQfh/KO/SHTCezWxAY/TArYea0ITsyU4PJajMgV/NWd4eKB2bjg/3glWVFcu4wY1FKokPlnLvsV0e6EIH2qaWyWn/P7yfUzqlqgIsGRA2vVm5+N9FnEoPkBDPwp1Rpeoxa/1hpP0ftjumoYofOry70WEa2Kjs64wdT5/tsFhUZ8B6v0RRd/liFejbbhV8SYRes62uY7cYtiHfp+lK/tMUUVP/TWAOjVB10d02TMKaXygR+5KJYtSYFF9aaebFola+s5xhlb02PvCSNC3r8ukZ5AU+SByjZ+mDY5q0clcQKSQNDbwvqwtmG5ZMCaBf6GEx+iDqqa0tJx5gvdE9Ok5SLWg+kiZRPwB8RP9AWxurTnENoX/r319qjNC/Aw6aV9SpAmjC1Pd9McpkmVAGqh6aUYeA36yKvBYMlbq9rF3mvfZn9Xu5ELkO1yCp+s3DVkU1RMWAW5E2B5LkUsBIWYeDXBqZrVi7iak0k0GOEobb7xnRXerl1oUU8eSTCdzYxgaufQQEYD2Z9Z5PCp+GACHQoW6uDVY+2nF/PJIJJc6uxiQuBSluY7rJMbuUvZtqzIUnp3yvTOihdbS6kbP4V5CSw3kZFt62XHYVin3Hg7aa51/rVrNIjFpw3iFNV7Mtx0bTdOSKNHdcfNidn14YM/2vOdHEFYV/NGWXMG6e6A67zWhEVchybrsKL69AxhAZYfy7zI6490vLM7pTHOGNKwXiZ2oaQPlp9YJdE7PN6moGN8/8LHZ6bEoH0boUEEfxb1oOkPYQjTPKU5FyEZHTgDkZ6AvsQ0kejnKsvYDvAb6PjQxycxtGT3EIs+3MYWDjjkg9V+L5NbCifTVBuJK5sHniM22fyY1sDzFSmCb1YMFBQq2smLHehc5UMUzaCA3g728cRiiqmMJJTyESmntUmJfVVrlOPvHVS1tSJuvGIinnOrFE3N/pRrfU5BOxqokTMJVa0/sVo1eKKVgMC6agJ86NsT+3Vqh1uRN1gfbjq1MwRz9higSC6DbwJ0kyagxn2byy15deda4wR78upS/2yBIsPmxts/+biJhvlgg9XClmyqK1LyeJW0HawtQBdTHTkFEIkw88RVKjjeZa/jubZFc4tfTt9tC+PYU/ar35KswwYtbM7SVgnlFZ9niQ0b2GgRgQinsFiZj3jJ7apjdNXoYJyrNfYuI15jUQtQPfB6C6nrK/ryzrZMSeEZEcgx15dYKj3e3xPCp+kI+CxHi2mHuYnlFMdSnqvJp8daRSQW/xe2LaklKSRSNaEmoxKEvTr9nj0piThuE9+6s7uzT1JfUTIxotocPR2tLssaYooZj4nwGIfI9km70m0iOchWLeXi8RqeVkZkpOo+Nglc2TJxFB5e8/jF3yMCpDAQ91FdI5IDaEfsYDg8apf2l57whtjYDGZyndG1hNaD6KHBEnbPFP7bzbMAuOXjPwuTJhbBwTaBFP1iz/JgmLd5nneFBFoaKKusbNJQEvoMul3OeDab80CiXn9SRmxTAOhswI8Dgh4NcWUFaZwhIehNtpRms3w7gfzeunm59HmMANJRc3RKIQ6iCcEYyQ5GXrVOW44TD9oI6FjCmlgyvVVQmW87sgsBsOuBfqK8yRo1heGhIssL3Neb2pCSfrn/38IbN3K5toTVNxDh6TG1WGrj6RgGPqOC62JqqUlA,iv:+KGKWRkSh8Z9BjQkVv/FSj8DC0wdTtbnzPGA5Ci1sBw=,tag:rznMZOsFqlK0HugEGcmQNA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-07-18T01:04:58Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgFJzsRjqu2WSpkbn2G0tk4jAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2rqJKbn6kWaL0aIVAgEQgDutUWwP3WamfNI49AAvDXg8b6FAs6qBwCJDFVdJzrujncR9Cee3YsF25exnS8XoV4k8gqStvgoobV89RA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbFFtNlVPcklRNG1UenE3
            WlhYekl2TzFXM2RCTC9XbkpMQmlZY2NNbjBZCjF0RlBDTm9Rb05nQXByeGxPY0FF
            L05vTTVKMDNRZ0o0cUdORWdHWnZHZ3cKLS0tIGoxNXNEb2dabkpVcTcrSkVXTXlw
            WDFWelJRQWZlWVVsY3ZreFNtTis0MWMK83h6O9oMMCV6zHF5FVzVK6mYDEA8GgB/
            8sl94woZw3DsJO+vtTFPivHlsR+lFLnFPu5+qXTt2lT8YC6v6h7FMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T01:04:59Z"
    mac: ENC[AES256_GCM,data:GclgRgVdCQ6zlcR2p7UPGNDitR8SW4Z6KtuLNE/tC6SSq/+kAsFqoOjA1JjOGAWsUdtTMFY4Thxi91xgcXk9LNW2Ev63705him2ch8DhM80Pg1TSY4xtH2gVtcxu5UWGz6skgcQjOBTWT98OYRbOvD4+PeObkh7UcsCjdUI6CMo=,iv:sZf/oR6mB7EqU+J/wWhwEitAWN5S7FfPM3GbfMwvBOI=,tag:sLnGSJuZMmxvvrZ6ebZ5YA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
