apiVersion: ENC[AES256_GCM,data:e9I=,iv:BReGrP3rQOm5ABjhY2jKZ8s+CiyYGG8swmBPRhQVJbE=,tag:USqrqJWj8TqbB3aYS15kfg==,type:str]
kind: ENC[AES256_GCM,data:fTSIs3Zn,iv:v7Myzh47/rNUS2WG6gFPcXqINnvnRwZGsGWwzifvIgs=,tag:4bD50xqyw3wCPRV6ONRzow==,type:str]
metadata:
    name: ENC[AES256_GCM,data:x+BcHHhSyfs9oA==,iv:q17INWpYRlY8IheXGBitEIiLR3bMn+hZyqMLU3i+dfk=,tag:1EYvko+diEAP3hhtwYEu6g==,type:str]
    namespace: ENC[AES256_GCM,data:4LHdxL3Qnw==,iv:D75+78Aj3BX6hoF4YV0eMjierQAthicuvXjqWIKBj8c=,tag:Hq5yF5DtNk2NmJldxsy8kA==,type:str]
type: ENC[AES256_GCM,data:XHwIrMxa,iv:n8EdUWaj3c+TZY9Fpf/4Dy0SWwAfc0AEAl7gYbPQoYg=,tag:nq7UUXDEL+HxBNq8p2MYzg==,type:str]
stringData:
    dns-api-key: ENC[AES256_GCM,data:VYCn/rWFmw5b6O6bGkfA3Bbmyn44zW8B0GVnSQOGeSIVwOSWzIFsyw==,iv:63AhaLdNvBe59QEC7RQ2FEZHBIkrC6t1crRGfcV4sak=,tag:wPbnzrPcfLaqgkXcECvgpg==,type:str]
    global-api-key: ENC[AES256_GCM,data:daOoHfq9au1DMbpinOvQcOL812pMdyK25AXINKy9AV09FNrzxQ==,iv:kodybbwDHivrRW73BcvnZ/4mT03MxKki/7jMwuiO9VA=,tag:QrgH+IM/szR5Y+b2OsL1MA==,type:str]
    dns-zone-id: ENC[AES256_GCM,data:uUaM4FJvcjQy5xDfGLHJ+CtYe4+f5zIRZTsPLfP+fKM=,iv:S0WSX1huu8veonAzl9ZD1zGlsXQ3kGhz0cdk4xaoYB8=,tag:ZT2ok/80KqxnuOmoXKSDug==,type:str]
    #ENC[AES256_GCM,data:EuVLtDa4yqnp7RHrW+i3sFrO6vM2WCYpQh2cc6z+kQ==,iv:/XJmwbmYuAR2vDq8sjm85dcrIETdOmHAkM+pY1QiXiQ=,tag:qYdvX/JY900OGdxkeML55Q==,type:comment]
    dns-record-ids: ENC[AES256_GCM,data:pP/BtwahnM2dw80c61FW4oQDfeFyxKoKsaTT9UMwSM+tx3GISOZDSCjfD9Gn9r1HlNCXEp+T7/yCr7UCZtPHMmNa,iv:eWly880YTEfqagwaeAK9ll1eJ9nthjQg1zbhYmI5loo=,tag:ymdz+xfC4yh3BZSdHiOoEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVGdQSldEM3djdWd4V0s0
            N2V6WXZBZXBOYUR3QTBYdjBuQUJoSGtiMTFjCkRsSXhoV3pxSXJZMm1ZRlU3Mjdm
            WHdFL2hZdGMvVzd6QUFlcStwc2taZGcKLS0tIHYvbDd3dUxXaFl4WnJPcjRtaTUy
            bFZsRUlyT2U2Z2NrMGNXc213eTRTQ2cK5YfSk3I9csrE/zJ5GZyLSHsp5t7LTC12
            M4FIogkDW7JbknFen6tpr9wDBsw0vjlHZ3siKdPQpMWXO5ZdzhbqPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:24:33Z"
    mac: ENC[AES256_GCM,data:F/7azNBNbRww/3gFufmErjzNzaDzKKPaMsPqPwYrx6zib9Os5rDrvpOwfu2zaqFT3QpetdCNwRthl+2YssCSO9/J0XxA0ADRpodjCrglF8JlkX1OYUxUarVqd+DPsGGB83hGug/Ikba72rd85384FHQHCkbn6uq4FlM09eZwvcs=,iv:NBIKJD4BMT4nCv1onDrnN8zadtX9fqgjXQcu933MKik=,tag:6jYDAXu1JatT9s9rw/RHSA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
---
apiVersion: ENC[AES256_GCM,data:z4Y=,iv:DR0GEq0iwJg3u8kEkOKypjYyRg3UQAFsd95vPgut8OA=,tag:cwKmScLPj9vUUZrRPZwuPw==,type:str]
kind: ENC[AES256_GCM,data:cA5IXTD2,iv:dXBwR8u1HtQfr5AcsddZnzoFWPfqTiUBO4QidgElC+M=,tag:WWraPhMpppvK1IgRQZsr2Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oclQnos/,iv:J+COsQFJRLl7QgPM9sutuAEtolHXmcyJTTkVvfSdEb0=,tag:AFIFZxggvP1ZzzTt3N2f+A==,type:str]
    namespace: ENC[AES256_GCM,data:HgaqF+Nrkw==,iv:+Bv/P7ptVSU+sFS61vvfBGkcuDnDayTNavT4AdtqO2I=,tag:8KhFYb9E/eagO4nTeHVy+g==,type:str]
type: ENC[AES256_GCM,data:uw2VKOEn,iv:Fk5ZFOoyqmebHPNXlXfSNqoII/tvx/5McQXwgi+w4CE=,tag:FsKRwVpuGYkzSmjy4iM+jQ==,type:str]
stringData:
    repository: ENC[AES256_GCM,data:HUGKLdYDED68v0Zy90brnJXvId3w3hD9gtVKDgBncOqmonVUMrNbLuRqPUoFGeFuQks2WzHRaxzJBkkrvrR0uA==,iv:hNh1zzaPDSbMYgdtrHMR3JXJuAcpnDZTrGyayJ7rk4g=,tag:zPPk+NSYxpFsugup/nEcDw==,type:str]
    bucket-name: ENC[AES256_GCM,data:aJx0kGDmx2F3whfoyHcq7hOhQ6qsKjKaOeCGEFw=,iv:yfRgLmqav/hdYpozNtGmhgc3VBmPJBpILGwFci7wXlw=,tag:J4QgzUA0UEMurBpeT6I2GA==,type:str]
    restic-password: ENC[AES256_GCM,data:fepTOrX173d9rkd+ZfQDLac=,iv:XBA6gA9oVmtFgumJ4K/SAmZLdiCPflAJdmvE5LsLsJg=,tag:x5jV/M+DSO8ldM8nu/L3jg==,type:str]
    access-key-id: ENC[AES256_GCM,data:hrDps4Fhwiv40RZys3KFsV17gho=,iv:8p606KEyqOyZ9JeVd38W4xa0KT6KDBsArelEas2H1pE=,tag:lpoA2UgCULrySyrEe7pgeQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:V794tQN/s/AA0fQe1z+ASIrQsLkMrxtT15GfsAPDOJUhwbjxtUKakw==,iv:mKLdYOA1KbmxFIyJTPENG58Ff7G/NWGLzcDL5A914ic=,tag:ENincqJDPNFhtAxYipzRKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVGdQSldEM3djdWd4V0s0
            N2V6WXZBZXBOYUR3QTBYdjBuQUJoSGtiMTFjCkRsSXhoV3pxSXJZMm1ZRlU3Mjdm
            WHdFL2hZdGMvVzd6QUFlcStwc2taZGcKLS0tIHYvbDd3dUxXaFl4WnJPcjRtaTUy
            bFZsRUlyT2U2Z2NrMGNXc213eTRTQ2cK5YfSk3I9csrE/zJ5GZyLSHsp5t7LTC12
            M4FIogkDW7JbknFen6tpr9wDBsw0vjlHZ3siKdPQpMWXO5ZdzhbqPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T23:24:33Z"
    mac: ENC[AES256_GCM,data:F/7azNBNbRww/3gFufmErjzNzaDzKKPaMsPqPwYrx6zib9Os5rDrvpOwfu2zaqFT3QpetdCNwRthl+2YssCSO9/J0XxA0ADRpodjCrglF8JlkX1OYUxUarVqd+DPsGGB83hGug/Ikba72rd85384FHQHCkbn6uq4FlM09eZwvcs=,iv:NBIKJD4BMT4nCv1onDrnN8zadtX9fqgjXQcu933MKik=,tag:6jYDAXu1JatT9s9rw/RHSA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
