apiVersion: v1
kind: Secret
metadata:
    name: cloudflare
    namespace: foundry
type: Opaque
stringData:
    dns-api-key: ENC[AES256_GCM,data:+BBLMrIW5mxFOWIS6KVkHjW7YcYalqM+3DVGwslI5l5FcaFQ/pn7sw==,iv:FGJ5d9rELGT9wQIVqzi2IUE+YCgklKx1hO6uIQqiFeA=,tag:gyT5C/Me+FKikSqhQABGhw==,type:str]
    global-api-key: ENC[AES256_GCM,data:kmprmPOqpuVtAD9MmQxOIzSBCiyzsqeZA4SCh1z9JC6Ta/t0lw==,iv:2LpSyIh3gC+oJHaANjZfi7GUhb7XiB4sWl33BM5U0M8=,tag:ZFBfdjgLrn7Z5wcX/dUgBA==,type:str]
    dns-zone-id: ENC[AES256_GCM,data:DfJdMLi7Memtf64W5M/jAwJlQKjPEpd9COqZ0Amdziw=,iv:Yopl6fpjEPyicAS1pFHReYmX70PfR3I1AxzrcCaUX+E=,tag:UepUrFWFgtBpFjz9bq0YNg==,type:str]
    #ENC[AES256_GCM,data:e+uuyu3RTTZI0xQ5NgXYOzK9NwCFHOcn/M7Y09O2Cp60l2het6fTYlTuwL8cjZgwBvDC,iv:xOXXy5zo/q6rIkWK68WWujMk3ZIDGQMtgAAuD/3+h/0=,tag:RY5nesIyAuDKBtNSQ1sQMQ==,type:comment]
    dns-record-ids: ENC[AES256_GCM,data:UQ5Sb2q6QM0PTkIiP84kNyoLwp7C1blcMCxrJOrj3uOCnq/qtdKK9FD9mlUn1sVfvgQGZOTAExS2K+PF0zllHFKdLQBe6Guz7cZHuw/3Sq5CZmH8DNnthsmYrX5MYOgy/Rgdrg==,iv:WGXsvioyLy5gCyzMN9AXYoqCD2p1z2il5+pCYyb04pI=,tag:87XQMwHpVv0buLDRY5+cLw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-10-06T21:27:31Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgFQ8/NzbeLL9kNo5uYS3bd4AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMCE9L6QDuoO3yprYAgEQgDu0GHAqXykNA0QCoJCint6zoPz8wwrU16dd2Rg1N8iFQXMA/hdyWGzm/3BE31g2u57ekuDK7Pq2SHMh8g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuam5jcDBuejFIT3pFdnkw
            YTk4VWdJTTVjRzMyZUtkNVdhOVh4TkdNREFVCkVEZEVoZHIvbTRoNEo2M1ZyN2Nh
            TFhmb2xwZ0FYRGw0dVQ3QXNBTTYvWGcKLS0tIGRJRlVOUHhjbVM5ZzkxaDdRcFZr
            NlhqNkV0NXJ3bC8yRnZtODdYNXpBT3MKFMv2bwfUf/cjwDRr7+ZsORfsaXgKpImv
            5u8Nmali+6665WfUCXVMC8XC/4vX7bcdPEv+Pb7OjltDLNE5CCYV7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T21:27:31Z"
    mac: ENC[AES256_GCM,data:0iLBbd2uiJGzqECwzySbanVZo2BUcUv+2vv2PK5FpjqfC8TGk+UB/gDmVMu09t2+Lv2DmHn1RGrwDdPcvkGsaXcssLAQiwWpoNfYDwvXbiTU2GGSmMwOPJlDqaZc7fdyzpCgBJ1ufJmL+mizoMVpaUbxQn3/pg3KV2GTb1Lxq9A=,iv:/E5Mey+1JFHl8Hhc04mof6/B3Cjx+vrtdo9fHMncYvM=,tag:LRRu7K1q1tlrrnHfAYHszg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: restic
    namespace: foundry
type: Opaque
stringData:
    repository: ENC[AES256_GCM,data:DzUikizfJGQnVDyaUXz0Oro1piweeaw1/lbKLrgDtf1G74N+CPKdWD2oj/qIRJbEiP3Ziqlw8LKJP75cQDyo+A==,iv:JGDQ/fC62skJuDEnzHxL/G0ADHE0R/dq4MzZcpgvLrU=,tag:Il49wQRe9zmxVVgok5/Ruw==,type:str]
    bucket-name: ENC[AES256_GCM,data:gfzatEGXgN0rV5K16OjQl9Zz5yC5XEL8gABEdVc=,iv:GVA/RZMh56B/HaekdJZsVWvIULsAlK/BKOB3dHUEyZU=,tag:MoO6Q51shcMOPbmneQtomw==,type:str]
    restic-password: ENC[AES256_GCM,data:m29E/7yygpxnRyCnFQF65nQ=,iv:nt2q/Z/Bf998VS//B4dTe2UmtWtH5oGwCgHPEokEJX4=,tag:eXRs/rB3tTQdaUXidsZHSw==,type:str]
    access-key-id: ENC[AES256_GCM,data:VyKP/y624EwAMnYXpiMi8qyvqJw=,iv:iLlH2a25reoPgICixPs3G1/HABDXX9KZXxpeNfLydxo=,tag:lKm97Mbj0eph7ti0M9ixZg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:p9PMwPo7pCFEN66qb1mnq3d4z7kIROTA6Z1ZNLb7R3cLta0ooAGlog==,iv:sqNNQ8f3wybycMnQJ3BOKHUkBmy87S5HiIWFcQ8kwSE=,tag:tKjwmomdTFI9SDq4RM77GQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-10-06T21:27:31Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgFQ8/NzbeLL9kNo5uYS3bd4AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMCE9L6QDuoO3yprYAgEQgDu0GHAqXykNA0QCoJCint6zoPz8wwrU16dd2Rg1N8iFQXMA/hdyWGzm/3BE31g2u57ekuDK7Pq2SHMh8g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuam5jcDBuejFIT3pFdnkw
            YTk4VWdJTTVjRzMyZUtkNVdhOVh4TkdNREFVCkVEZEVoZHIvbTRoNEo2M1ZyN2Nh
            TFhmb2xwZ0FYRGw0dVQ3QXNBTTYvWGcKLS0tIGRJRlVOUHhjbVM5ZzkxaDdRcFZr
            NlhqNkV0NXJ3bC8yRnZtODdYNXpBT3MKFMv2bwfUf/cjwDRr7+ZsORfsaXgKpImv
            5u8Nmali+6665WfUCXVMC8XC/4vX7bcdPEv+Pb7OjltDLNE5CCYV7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T21:27:31Z"
    mac: ENC[AES256_GCM,data:0iLBbd2uiJGzqECwzySbanVZo2BUcUv+2vv2PK5FpjqfC8TGk+UB/gDmVMu09t2+Lv2DmHn1RGrwDdPcvkGsaXcssLAQiwWpoNfYDwvXbiTU2GGSmMwOPJlDqaZc7fdyzpCgBJ1ufJmL+mizoMVpaUbxQn3/pg3KV2GTb1Lxq9A=,iv:/E5Mey+1JFHl8Hhc04mof6/B3Cjx+vrtdo9fHMncYvM=,tag:LRRu7K1q1tlrrnHfAYHszg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
