alloy:
    mounts:
        varlog: ENC[AES256_GCM,data:BoqEPw==,iv:To77xpU6ogOIh6vdlGy9l8UzSQytdgFy5aLOLvCLLME=,tag:8/RQ3BoC2aJMSHKrruyMgQ==,type:bool]
    configMap:
        content: ENC[AES256_GCM,data:w3NzN819dob+RAZVcda168B0I3qTK2aOzSPQ/vzpeWlnU+EIChtFycbyk2WAEFYELZcWsXIdUFPMHVKfc6r9SfHPvLFRqzpwt08tVpheeCm6j7xYTfRrqG2gKjKExAvYW5x7boaxv8zR/7goQthsQeLOCpzBdWmwFUCi5raIlLn4LtEd6+CafgJM5UPy3ECp64do7Y/lbJI+2I1crnTf1NWTeje+fP+Xt2c8B5KsUSIQ6pbfiijz+wc3qCM4JvWknJ6xDUtrO9QsZ4cMDAbJ3c/rwCyUtXyKcMsgsBNPpCTK3a58kbio45kGoxEZvEirCXU+gJ4qim7MQHR/j9pfYVWaGmeKh5rnLGOzOpz5zUJRed/VmY8cIf2oLAPdN265/IHk3wTnscMT8Ah8IFB99D7s90IHJ2XfW6qB+MSnezexMPe2OzQLyMMWYrSXq0hIy1AgNoWWuOQ1+3ZzDH1CP093j5M=,iv:TGAdSCYvWYdpi+eNrrI5P8nHYT4zWyp83rov59D+h8w=,tag:MKUI3wPPPN8fih8yBCBsSw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-06-28T03:55:07Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgHLGXNhpOlaoOj4OQcBjMlDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMx6eIlBNnhxSd89DOAgEQgDsZJ+99NJh8lq0r2QkHYmbhQqjNXFilBCmax09xuWzc9qup52ietdK69jZDqtf6I5DPDx9JOBpmpgkn3w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUanpldUc4a29sbmRtd1Yr
            SG9JZE9rdHVOOWgrbFBHcnhqUzhzbXNkaDFvCitIVGdiL2I3bVdaWklYQWluMkhM
            Nkp3RE1xdDNDaVRKdERFRXdBNDNjMDgKLS0tIC94R0xzR2JaUWFwSHdKbHZuUkMv
            ZThCWWNCU2dGdUwrMjRpZFdnQzRPYlUK7qI9RdTgAPJtiLMx0oWX2TbCUwOVIYmm
            ldMlj5Mi6X1k3CXRZ+wmkAwCiVN2ZbgOzxpE3HiCiiA8Iw/E5rdsew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-28T03:55:07Z"
    mac: ENC[AES256_GCM,data:FNIIghhCEmY8iSIBehvut/efiv3Q5t+C0lbH1T3Uy3lqaJ8zz7onq4fAuj945mIqDJcYoZJfPr5ugBQoGI4/kBQHka3ftPVsU63X80M+/lW7ybEj1fc1pJtNzQ2NOgWVzubgmzd+JR7s5xrmnVJ1XQafeCsuwoquHcTMF8ESXZ4=,iv:ZsJS0eGU7kSZ0rsU5bbUG6eu85swGYDohIujKwI+3Qw=,tag:1MHkkCwA2Vsf2mUICANYKg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
