loki:
    commonConfig:
        replication_factor: ENC[AES256_GCM,data:Jw==,iv:Arjkr22GPLvXFJlbcr4HFHmcLtzgsWDFc31cozK8Yu8=,tag:t1kammfCOC7kSBKlJpiT7A==,type:int]
    schemaConfig:
        configs:
            - from: ENC[AES256_GCM,data:fXE0FB4PD/PUXg==,iv:F60EkKAe80uTUCPP6BdPZzyIcZFxkm5r2wzzGHjbuLc=,tag:yoHCKypzIhGYFBDdw6HQ+Q==,type:str]
              store: ENC[AES256_GCM,data:xme3Zg==,iv:PrqfQiptbZCKA6+hPo/nvPCLr2bzQ2yV6xovEPkn8Cw=,tag:V+XqXCe8jAaWaU+xSi6f+Q==,type:str]
              object_store: ENC[AES256_GCM,data:ULY=,iv:zJji3AnDYaz+HST1Ctix7O3TLGpfqfSf9D3s3UKtwoE=,tag:WYtrNfTO023qx4b+jwZUTQ==,type:str]
              schema: ENC[AES256_GCM,data:n+sx,iv:wrkxoqRULHcgPUnlfhwmlvkCfvYUOfOA+08TIQQ578U=,tag:jdm1cyezGT3x+MsmwNW2VA==,type:str]
              index:
                prefix: ENC[AES256_GCM,data:IXrreSVXmxVcUMI=,iv:rh6Q1jHYcJjImIsx5Ffn3+isYwoU96eGU8Jw96+hV3Q=,tag:0HPzHiipZM8nFqTdRfC3uw==,type:str]
                period: ENC[AES256_GCM,data:E84y,iv:PS2c14hFuXg2r8dRwgQTKlJyPcZI2jjrl7ArdyLUDR4=,tag:FizXIfoMs1DxV6JuOEZlww==,type:str]
    storage_config:
        aws:
            s3: ENC[AES256_GCM,data:lDS/CSpeupvL3e3juS8=,iv:RVakkK38Gq7+l/D/ZvaRrqWNQfTCAcefPJcoeP06VtA=,tag:8sB3CzqVkOf3I5jg68WhYQ==,type:str]
            region: ENC[AES256_GCM,data:aq9exacpsYSr,iv:KNuvqhhEa4NeolM2tSakVbv7TFgI41caVLh094Mpad8=,tag:IMqLhDztswR9P+O2kdPOiw==,type:str]
            bucketnames: ENC[AES256_GCM,data:9vaeFIcwklL3nYlvo+iN82BBr7voHDdApxC9mMGH0ikuNQL6zQQv+uJZAHWG,iv:v8PFfrkf5rBq+ZN2GN49d1bek8UmdMZhl2J65OlIrkA=,tag:U1xh8rcfnRpxIqpTYoUaqA==,type:str]
            s3forcepathstyle: ENC[AES256_GCM,data:WPv9MqY=,iv:Aq8RcHr60L0mGYBEBIq5WlcZaMufNGG+vw/qK2pd60E=,tag:xlwjz5Q73ijm7Z/hd98CHA==,type:bool]
    pattern_ingester:
        enabled: ENC[AES256_GCM,data:4v63Qw==,iv:kT1G4gldLfLWYuX9w7asf82MUaT9quyPY+IQBi+LTkM=,tag:hiUkb2zVFd+NgyqvdE06YQ==,type:bool]
    limits_config:
        allow_structured_metadata: ENC[AES256_GCM,data:IOqxSA==,iv:OU+cCwLZkXykbCgy+2MZi8qhk5TyWj0A9+RtD9JTFt8=,tag:ydRaO4fZjCnIA4LgtEkzyQ==,type:bool]
        volume_enabled: ENC[AES256_GCM,data:r4BKSw==,iv:vpumfg+HnASyqt4yG6ZjY7rOYhF5fiFyEu6VxARKtyY=,tag:V1ELEPtYV7gtWC7pcpWd4g==,type:bool]
    ruler:
        enable_api: ENC[AES256_GCM,data:Xdtw/g==,iv:tM+OzWdbnA4w2ide5QQ24k9rixYXJ7VywW/Px6tNQYw=,tag:2dFW1eIjhUegOjj0Enk7ng==,type:bool]
    storage:
        type: ENC[AES256_GCM,data:saU=,iv:WXfP75V67QFl/9DtKBaWG4e9Cc0IhjOoR4BKsf6nwfA=,tag:4OYuRBiaX5JQB5E0F9JZMg==,type:str]
        s3:
            region: ENC[AES256_GCM,data:tqNx/MYLExiX,iv:p/Vjcchnb0uf9WlDeCqzz0aZVHiwZK+fdyrwMO39jpA=,tag:JsRvJdbJxpseKMU1nohGhg==,type:str]
            endpoint: ENC[AES256_GCM,data:/NIVP+QS1SmVeZBU2+CK+aP3n/Wv18I49B+X9LmsiZbBiwk=,iv:OyUF2y1rIYnftR+/cKMPVl1jn3P411wHV4QI+Suqpqg=,tag:fmd0n1Fc7whJIx7r4bceEA==,type:str]
            secretAccessKey: ENC[AES256_GCM,data:R1lcDzJFFg75d+1FLMXpS/Rg8JaZvWpmkGgywktJ676bqwEVIvbgyA==,iv:8CBgj+j+A0XtaEmStxd8A1GXMG+gcpbpkU2s+zk/Df8=,tag:Wu/CuDvDj3aKNiyinECQSA==,type:str]
            accessKeyId: ENC[AES256_GCM,data:nHwUTidy1jVwrUfls3oXxM14yEg=,iv:4VC6NlX4hRymKWDrWZPLBIdoQkyNsSs6OdAflco8Di8=,tag:k0ue7462djnAKrTHYewerg==,type:str]
        bucketNames:
            chunks: ENC[AES256_GCM,data:9BAzorQWDZpt+69XnL4SMpMIn151NlJPgHVVfws1l7Cyee7TIwZIUuzHLZ7mOPDdU1n+mA==,iv:q3PSoLIGclqSyRmvmqwRwJbgUhfJiCBSv+BO4uojinI=,tag:l/dGE17Tt+hdhSQ2F7Ofkg==,type:str]
            ruler: ENC[AES256_GCM,data:ETcm/j9e4DtIos6qQz5dKu1OthOgMRV8S9LMFJu23NqUGB1cekhY/CTD5npjpSlLqqeq,iv:6O6XE9D088aQBV02MlAy6p/qiH+JzmMyYBmoOZU5Iac=,tag:1JpsP1pLQQ9NLZHg2dfwCA==,type:str]
            admin: ENC[AES256_GCM,data:ZYAsrnHk6ROQ/7VA0Thz1eEGNFaM3sO1UtVu9qy075ufuftT5OTEAYDWJXpSdgVwkEOL,iv:eyko+8EWPBWQPlDmrSorh6E8H9XId827Ft+lrEnRzKk=,tag:4eFV0V0MnDebNIC+0Vo4+g==,type:str]
minio:
    enabled: ENC[AES256_GCM,data:eKUZ9es=,iv:50qJ84Y0YiGIeXz9/5fuDhtB9tMnAsAULUFTXF27IRs=,tag:cKuzPaf2rT4FQxcWHh+/3g==,type:bool]
deploymentMode: ENC[AES256_GCM,data:hrrJhTcpPjRhFjbQ,iv:KL2fLTB+HoBv2xcR2HnuM7SnY2zkhGZ7YoUmmBBEIUA=,tag:lUsJvEPbesb/QIS9f7rv5w==,type:str]
singleBinary:
    replicas: ENC[AES256_GCM,data:AQ==,iv:amRFil7/BSHwt8M1gAarWhdF7+x8R1GdOsl0ZpMvoIA=,tag:qGYbPraG4fhDHT+aMz5vGg==,type:int]
#ENC[AES256_GCM,data:VpKr/vPLc5GRdbl/4rPEGV4YupYu4WYBJMbZNi1o+z0yIm56Uy8mzTB4dd91hK3Rm1k=,iv:gFX3Q6KcCNY4PDNRm3JNDrqEbOhWzF1u/OqweUcJrqU=,tag:CAKW1Vi+yj8GkRYuwEtQdA==,type:comment]
backend:
    replicas: ENC[AES256_GCM,data:9w==,iv:qkIS4q+VxduxJ43wdvvqMzm3da1rsNV/3YAq+Q9ilRs=,tag:KBJeSHIoiBmPd4PfDUn7Yw==,type:int]
read:
    replicas: ENC[AES256_GCM,data:7w==,iv:6l/4/hv4P2oiBd8mO8rblYlAC0op6IBDucPgshAqTfM=,tag:Tc4IMwNAn1x+7Jm3+VxlGw==,type:int]
write:
    replicas: ENC[AES256_GCM,data:qw==,iv:TIWbKtIQRsUOa/DsqpAZHUZqes6+Wl9yOEWw4YvqOKk=,tag:o2EEbivmM9V9rHtR476aww==,type:int]
ingester:
    replicas: ENC[AES256_GCM,data:sw==,iv:Hm3RMGPxUjOpcHj9VlRWY75ED8wZQoGpmFdnG1q20Uk=,tag:cuI+xRc56q8J6kyqQJPbIA==,type:int]
querier:
    replicas: ENC[AES256_GCM,data:kw==,iv:6DKhNSJhn69OkA3pf2W65xUC/l22KgKQcEMmx3FA8fs=,tag:UT9SowRrl6jWsQUI73cMwA==,type:int]
queryFrontend:
    replicas: ENC[AES256_GCM,data:cQ==,iv:mBArqMYnz+S4HhmZCtUFSJeRvQWgmq+/pilCWaB2bzc=,tag:ekfIaA4zJeudldHx1T8QDA==,type:int]
queryScheduler:
    replicas: ENC[AES256_GCM,data:bA==,iv:JTxRH/5/3hHoCoZ8QBEFH/D6Hda8w6XzzoktjkugloE=,tag:azTdBelCGvD25HVa3/2aMQ==,type:int]
distributor:
    replicas: ENC[AES256_GCM,data:lQ==,iv:6rv1FBTXn6VgUctSrhyIf35PimfIeb0hRF/EC7QTkM0=,tag:IxCzevPTYLyG5JvJX9zFig==,type:int]
compactor:
    replicas: ENC[AES256_GCM,data:/A==,iv:wfJ+Q4xvQSDE5Zv/d/gh0+hDg4jQfhOeI3A3WujL39Q=,tag:uPfcE4chS1AI7SoxVbrfiw==,type:int]
indexGateway:
    replicas: ENC[AES256_GCM,data:Gg==,iv:dnHPtwLdFyOzpdv5NToltufaYGXLOLVy/+3AsfAHY3Q=,tag:lKNOUCOMPvU1LVutpqXKWA==,type:int]
bloomCompactor:
    replicas: ENC[AES256_GCM,data:fQ==,iv:uX8xdrL/ItVPzlnkuuR3hSdpcbeV26KCi1B+wxakAqI=,tag:jx6eHrSB8s4bNQilMucytA==,type:int]
bloomGateway:
    replicas: ENC[AES256_GCM,data:Ag==,iv:waDpGFQ2tQYw6eRaiOt4KpzKQoZuTd6e6KJN+uN1Aos=,tag:yjTILTX/M/4hIoc35QUREQ==,type:int]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-07-02T05:30:25Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgGEwD5Bc7IMAuu3TNbMzPjyAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMLmfe+x4mazZZ/Q5GAgEQgDsjG5CM5sMMwXtvgaDoTSr9gsZoarBoMaRM4mDLkc2T27taJfwC37NL+U7ngjWeLicZ7Cfic4SqULY/aQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFem1wdFhsNU56ZUx6TjMw
            ZUxsN0N6dlVTTFdsMHJwejIzelF1ODAwRmdRCnVaZFNuNHFsdUR1ZXBITlVsRU1T
            MWhDd01rdmxLWEdDbXhUWFFYSDZtelUKLS0tIFpSbStqeGVScjd4bUgxMEtjT1dV
            Vjd5YnZvVnpDdG54amFyalNtbTd0Y0EK+LFqN8JLX09lRPeYa+9j7AtqmTSjKXA7
            K3Olb9Cjc6tVLeL2Qm/kbsbga/3xGDpyatDzAgDv1Fw+DlRfTSsM6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T05:30:25Z"
    mac: ENC[AES256_GCM,data:j16As5fp3FVW+P0kpncP9pBRwSSBxFFr9NkNyT7A3CNlJP/UT7W7Ao73hRph2eyEHDt4Pulk3JKCjl3vJk0AqgzUfTmoA/+metD7vNmVdmfQQayQ6IcvtjYh1Kf4hhBh8g4g4Opt5zTOenCnWiGoFJAKZOea8rVR5suxzxi5XKI=,iv:6YRezmdmJLJjbEmGkCCWj0fpXWQ0N1P8QNHzhvuphho=,tag:pgK7aR/oaFE6eRm6P5UYOw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
