loki:
    commonConfig:
        replication_factor: ENC[AES256_GCM,data:6g==,iv:ChTa4RthTj80FB+9f7aypc/adagwbFK1kd/9nkxdY/o=,tag:XzrTolHwO7DnPmKyaRFd3w==,type:int]
    schemaConfig:
        configs:
            - from: ENC[AES256_GCM,data:1MvWMR1SGAPXHA==,iv:08CtMyJZBw5KqZobV/gZxn0sq3LlmxfQby89hGgD7J4=,tag:qSsmGyJw5JCnF4vKljYBDA==,type:str]
              store: ENC[AES256_GCM,data:8UM0TQ==,iv:r0fkMgqWF0bBb+B6LzGm1Cqf3tNP8PaIIkhos1C/Emw=,tag:yRv3ITCWD7ApaaZ6gK5BXg==,type:str]
              object_store: ENC[AES256_GCM,data:cO4=,iv:sovRT3hTouoq0DfVAUJ3P+YQlwgblaB+t1R8E1d8kiM=,tag:4lVvyOd0WggM2NE932rhAQ==,type:str]
              schema: ENC[AES256_GCM,data:BqMm,iv:x+l7L57Q4U/peWor9se6W4wXHvrFb9GZdorMYW21GHE=,tag:svyElPuyPx7E4lGD8Aa4Hw==,type:str]
              index:
                prefix: ENC[AES256_GCM,data:hGsMyVbfvlighvU=,iv:mxpmoy32RmllAYDmrTIfKsmY8MD1VHBxoPELgoN8uTM=,tag:kuC2w0hpf+ZiEnOFM1M0QA==,type:str]
                period: ENC[AES256_GCM,data:1EvN,iv:dAUnvVGqsOLEJ38sX2kKRDJtHMmB63C8NIuzs7KEyGY=,tag:Ftmby/UVRM9p4ySqmUMZgw==,type:str]
    storage_config:
        aws:
            s3: ENC[AES256_GCM,data:eeSxQ5ne4Kc9yeXfBdc=,iv:QVHRO7FotxL30OIUWOi3TmyTaNW81z5mILRdOKisNHU=,tag:5nk66LuzZUS/UKQ6kVd8Yg==,type:str]
            region: ENC[AES256_GCM,data:FVP1ryxYmTkx,iv:kkeHP8DyYGFnOOSGl79M5xaRuGJWNaEdEdyIU26vF0Y=,tag:LqPydDxXX5LtMpQg07jDZw==,type:str]
            bucketnames: ENC[AES256_GCM,data:eZwIGZcGq5el3JSdjn/cy+4knLCjSL0Q+dGT9enHWtWsMBeW7m/eCpH/VqD5,iv:3p6f06L8/YdscOt8tP7+Y3cceNWFKyrAlOnMYppTIxw=,tag:pLQLnG/MzGY2k1HIo8/Vcg==,type:str]
            s3forcepathstyle: ENC[AES256_GCM,data:n31xt2Q=,iv:kXp73yAPnTbIsGvudtm2Gof0ZcOidJi6BNN8fG1UTdU=,tag:Gmdd5MFUtkKmRbXyfamibg==,type:bool]
    pattern_ingester:
        enabled: ENC[AES256_GCM,data:Jq1Z7A==,iv:FGbRSX6op9s6wAYSVSS6fZtuCuamy9RBzKNMQgEHVqw=,tag:UFM/MyjW7BUjifq1C0crRA==,type:bool]
    limits_config:
        allow_structured_metadata: ENC[AES256_GCM,data:nUrA4A==,iv:k2ehNJXvbIxFY/6UUZKUhNUZrkwWU45FqW2wMKGvcR0=,tag:EG1rjF4KrJ8V0mQ7KBRghQ==,type:bool]
        volume_enabled: ENC[AES256_GCM,data:UObE3Q==,iv:jHQw6zhfTtV4nA3Jf/8Otkf43gPN1ITDtqJEk1WbQq4=,tag:kfpWqz2L67iDGW/jhKsIdg==,type:bool]
    ruler:
        enable_api: ENC[AES256_GCM,data:Kt3Pgw==,iv:1JzBU876QZ/NiHiWjm4lyyHQ5PpDyNZ9Rka86t0yefs=,tag:hFHoAwskHB3AeB5gzUyJQQ==,type:bool]
    storage:
        type: ENC[AES256_GCM,data:bFU=,iv:v2RRKbEVD05+rhJijGy+wVMzmbkP+ROh/CWWKBjzdRk=,tag:5cSyi3rqYL0CYnqK5VM6QQ==,type:str]
        s3:
            region: ENC[AES256_GCM,data:It6CcvECFOt8,iv:YQrnNzZjqPyDR7mqiptlTyDvt8CkE+lGGU+a1pjkKJM=,tag:JeD0Xy0UnscxQ7PBER7/xA==,type:str]
            endpoint: ENC[AES256_GCM,data:4UPlR8GQkFfXNmlnxRcyCMj6tsARDrbj+c9JBWX49DGMB58=,iv:sm7GCEcbNunLNJtJk8Ht9cfkk6DgSRo48ZotuKLZo8I=,tag:27VcOQCItRNodXZ9QWHqNA==,type:str]
            secretAccessKey: ENC[AES256_GCM,data:txcDKbByKHeCGK/4jtJ2YIM3+Bevh86Lf+wA4jbA6JIj/e/khTdK6w==,iv:I7YDQ5CT4bdzRUKWTv7Xy1TIJuYgmz+BGH2GbKkpZs4=,tag:1DjXNNqtjBTMm7zsIM8jBw==,type:str]
            accessKeyId: ENC[AES256_GCM,data:ewbGMx+Hhuq+Vxi10hm3wv9paFk=,iv:3KfoiWh8CSG0HrWElYTjCFGPGECm1JXVqqqq5/JA1u0=,tag:hgmkuOa4wkjWgK17zCEGjw==,type:str]
        bucketNames:
            chunks: ENC[AES256_GCM,data:KxcBBI1tlzcEsEyftWYBdc6k6nJrXh3hbMrIseYHgBxCtOqtV2ZHGy6g2Un7kHifPgU8TQ==,iv:lr7vA6RMPBngBzkI3/Yi8OavHH0v9RKLTq5j624X0dY=,tag:+BhWDB/D0u19dF16fUsv6A==,type:str]
            ruler: ENC[AES256_GCM,data:pBjJS688S8oWIsLfU/ks9ung4OK/Tq4Kuek3rLqv03EFteE5524EUc/lkMcxHAx1LIdg,iv:4Oq5+gMZHLDuh3nzCiWQ/grLYMICCtHRbZyjlQYgOFg=,tag:QSF/PSRAhB0oafInL01gzQ==,type:str]
            admin: ENC[AES256_GCM,data:1VWpQnDZB7a54UBGQwDDG15Iv5Ok8WyfbBLbiBDBXiBYBWgxgLkmTjKphGHDtQdHSWQB,iv:2eBR7n6nN1EKi3m+LBNlKY5JgcG6Q4e/0CA19wju1mg=,tag:pN/LKiBkqnxcfLdYxn+ZIA==,type:str]
minio:
    enabled: ENC[AES256_GCM,data:TDkkU1c=,iv:FIg6YwZsPt0Bbe7jJFnWPL0M+14hIcin6rbKRnjgS5A=,tag:OxyCtLGbtWTLl1sQDBs6ag==,type:bool]
deploymentMode: ENC[AES256_GCM,data:75uKnbibSobUGrXG,iv:xVKP0NTF0vwxdfKTmZ+iArI/4DPIvTTC4gji8cA6BCQ=,tag:hxZTofEAJ2pIbZa5WtBm3A==,type:str]
singleBinary:
    replicas: ENC[AES256_GCM,data:kw==,iv:LG4O2JSYBr3XPAo7o3SNDs9wLHPQwW0LZmdw44Hrat0=,tag:D8QcNmWbJ/jIGT7kFGdNxw==,type:int]
#ENC[AES256_GCM,data:7YNZERgVBZlouofQ+jPbdJ5vu3lGZZXQJK9HeW9gde3vUkq09abo+H4xX/zFFYDYZoo=,iv:fcovkknYf3TAyEemmczlrqYZrRWwWPLJ9DnUWD8UgFU=,tag:ZCj3dowLNgGQrareNGn+sQ==,type:comment]
backend:
    replicas: ENC[AES256_GCM,data:cQ==,iv:RGP1nTgdpeLYB5vplUujTrF+GxFdWgUxiW1oW+mT/5A=,tag:9u8ZcEpshCIGnuSdbphJJQ==,type:int]
read:
    replicas: ENC[AES256_GCM,data:aQ==,iv:lqVWIXk23jnVVjXXW/v8RAqzV7q7JoemndafCBqh4RI=,tag:wQXtGQUUrSXLIPCnKpbxpg==,type:int]
write:
    replicas: ENC[AES256_GCM,data:bQ==,iv:8H1F6v8lnFMMivKNH6VUDI0A2ExhbH+Y730mCZvMfWw=,tag:KIQ23Z0J0JvVdiZ5gTDruw==,type:int]
ingester:
    replicas: ENC[AES256_GCM,data:BQ==,iv:20b/Wf1Wm/1vxB5f4V8slc/gYIQnASTzcSPJ7auEvfY=,tag:TyINPlSHTIQ0HXxDj3fOoA==,type:int]
querier:
    replicas: ENC[AES256_GCM,data:+g==,iv:dxHG4vI46dSsJD9iCmn/65MBbsgKg7Tx9K+UH4dVVKU=,tag:e9OhMu9Fk6k1NyrF/sFp3Q==,type:int]
queryFrontend:
    replicas: ENC[AES256_GCM,data:IA==,iv:tKw9zXkwnHa0OEuGrK2G8JYuqxjr4FaacjTmxJKWMEY=,tag:jNZnZTwkw7WHws9T5NfHAA==,type:int]
queryScheduler:
    replicas: ENC[AES256_GCM,data:Jg==,iv:xCaPZ8+BBAAy7Wr4yOOdGJJ4FzA1U0C9Zp8B3F0L/dQ=,tag:lRrVk0wZLA3cBOlobbMC1A==,type:int]
distributor:
    replicas: ENC[AES256_GCM,data:Aw==,iv:zvkAWPH865/p79qk+DrHNr9rCUmpJZDfl5Xw30ZKzpE=,tag:LTl8vPP/7ps/ocDkQktmYA==,type:int]
compactor:
    replicas: ENC[AES256_GCM,data:Ag==,iv:r5RhZ6OSxb4KAJLNt/lpd5uKiBgIEE+DB9fM7S1+crI=,tag:VLmJenUVfwpHr5BeCxE8Jw==,type:int]
indexGateway:
    replicas: ENC[AES256_GCM,data:1w==,iv:PXdB3pEfHze/pIARL0UY0z+OHlJta3GdcECGRdHnCvU=,tag:RGYJGtojC0TDjJq471IzzQ==,type:int]
bloomCompactor:
    replicas: ENC[AES256_GCM,data:iQ==,iv:6e6pcpuV+0WU8GRRTZ8zu+fUkZswNc7YZ0KRMzUFDLE=,tag:ci5Kn/xWUCJ8padM4rWEIQ==,type:int]
bloomGateway:
    replicas: ENC[AES256_GCM,data:Lg==,iv:nvgblRubTIVuS6KSgaaapYl919M6+yNrAtHJ03ppQU4=,tag:i9oCAD9QzW+GtPOErcjVTA==,type:int]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-06-28T03:55:07Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgFtlkGcPrJBY4Q1SvFxqKk6AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNOx0LHcrJF4KA2DbAgEQgDtUoCSgZCLL/zBwrKamOM7jplSsRFHwu5YoqQZcFHKaG3gxL1UopSEEtIzaOwbtCWmFBVYf2q94oDdiDw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NWZickJUbDloMTFSY2Y5
            aENVTjlaMW1sOGRmZUxCMkY4amlBWThiOERJCjJNSWExUnNZQkh0Wkt5ZlQwRDk4
            Q3FPQ0dFWHUyanlmRDRXOU5XazBmTjgKLS0tIEFwQ2R0ZlJpVVNOT05oUjA2dXVv
            WlkwSDdJSGk2czVIajNvUGdqUFVZMG8KML0/R6RlK6FUaU/h8xPWfh123vJKnYNN
            kp3oq8TOZQ0xsrxcWVDLVEdEX3hdbkccXLMmIa2HP6kIELXiWzFySw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-28T03:55:07Z"
    mac: ENC[AES256_GCM,data:cmQKH59lOD9n++J6ozwLtRvM0bq/l6UP+0zXRHLkFVb0XLHzYivPMV4l7kiq4+wMTFTbJ1r+7KHdKpHql0G/fqEd9oCBRF1Ac/9Egpp7bnxyesIBiMcZrrwsh+iTW2A1/a21pg5grN9mtFRx+ZVUpRiTxmPsgErhEF7a+a48C3w=,iv:mLIahnDcLClab6iWd1L5UsJrZkBne0/ARfluENQe3Oo=,tag:Up3B+QbQ9uj0v3dHlHSKqA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
