loki:
    commonConfig:
        replication_factor: ENC[AES256_GCM,data:uQ==,iv:to2dVQhpLqp3PXPEPGnLDH7dHoogmCnYmOQ7sq4JX50=,tag:tndWuJUt6NMxqhkdoOqXSg==,type:int]
    schemaConfig:
        configs:
            - from: ENC[AES256_GCM,data:X/vOkjUGjm8uWQ==,iv:jbq1zrVxRQSxXSxP0osiBjzTVYLZOiscI/ftFUcsoVg=,tag:5UD5cCqOlvg3+Cmdms70rw==,type:str]
              store: ENC[AES256_GCM,data:v0Dx/Q==,iv:PkkaTmGNxa93Ppg1ntI9+SHGGdPDpiYBK+8XvV4oL1Y=,tag:EVJA/V8JOmv2w4XBqT47IA==,type:str]
              object_store: ENC[AES256_GCM,data:tuc=,iv:+BtyMOYf+uCzjZ+AV7jcX34eFIkLyKBt+XszysSovrw=,tag:VbxW1Gr8TcpZfZc4NBA/lg==,type:str]
              schema: ENC[AES256_GCM,data:dz6X,iv:T31flDUQ5+rSf94tZhPdMnbDDufIEKloQLaoUkLZtqI=,tag:+h+2cgcWPv8q6oBaDbs/9g==,type:str]
              index:
                prefix: ENC[AES256_GCM,data:TOIO9OZldtREmHE=,iv:hp6G8o59f8BYuMTyPRfnxVntQNoj+mTRRBiVJgMe49k=,tag:Wf0RroEdl32+ZjHKXtUZag==,type:str]
                period: ENC[AES256_GCM,data:yB+O,iv:Z+PuM7SHntk328WaSX0PnZ9ir3h63xhQ5YpwALmnCHY=,tag:FI5zKWG+RKHAGbxZxu6DVA==,type:str]
    storage_config:
        aws:
            s3: ENC[AES256_GCM,data:HsinLvjWVwlrF0i0JNI=,iv:H4K88YYNyMe20fuOKGK/Pf445xB49e7oTH+qtrJ/20E=,tag:vav3A936/7AghiAxbbnbVA==,type:str]
            region: ENC[AES256_GCM,data:hktEQeigkpwj,iv:m4+Rh5wY89JS4ewS46MJG4sPj53NokhqBBshuJwH0Kw=,tag:6aqrewjOwxbuo3kzgcxfiQ==,type:str]
            bucketnames: ENC[AES256_GCM,data:TbEWpwxWHspoUfxdY6/zkvslYRpuvXSDJQWT53nFLXlhk2bO/oByUcANkT3F,iv:FmbkkWLqm9MAxL+Q2HW8oJuGKN02oFaG9Yc6CNuze2s=,tag:1OpgrD6z4hcQKzzJ7KUWeg==,type:str]
            s3forcepathstyle: ENC[AES256_GCM,data:xIQ3Ods=,iv:KIgSP3KigtiwgOgcCOi4OiTzuPQOW7hkcnqIwzABlcI=,tag:ZFO81gfdIxkEUYKJRM/F7Q==,type:bool]
    pattern_ingester:
        enabled: ENC[AES256_GCM,data:kGh5Kg==,iv:wuWKpktpp6iN6sTWTcrqYz56F4PsgnXMs2jgxB7yCYQ=,tag:sNisYBP0ZClVmacplU/Jng==,type:bool]
    limits_config:
        allow_structured_metadata: ENC[AES256_GCM,data:G/ZT5g==,iv:dmeT0GtidGZpNN6JVIgFFmQQlNMWSfzuiCUgdUK+dgE=,tag:t+I4T6wqoRhpo+Y7CQ275A==,type:bool]
        volume_enabled: ENC[AES256_GCM,data:zkcA7A==,iv:QIFs3fZJMiKiLXenUJRbnSPv2KoPVftiVL1QujrlY8s=,tag:mzJWNBU0bRdvPW8nchmpoQ==,type:bool]
    ruler:
        enable_api: ENC[AES256_GCM,data:ed2oLQ==,iv:MqifmatVyqJoCHfUCY+ZY4JOVi5r2XocA6htTJj57Dw=,tag:mNREhHcmYD8shOHB0CC8BQ==,type:bool]
    storage:
        type: ENC[AES256_GCM,data:VO0=,iv:iVy+24YPUxlKRE/qVBZtUlNxVzxi+FPnHZX/E9l2oRI=,tag:N2sMDLjHaBRWjQY6VH6h1A==,type:str]
        s3:
            region: ENC[AES256_GCM,data:N5sx6GF8oJ3x,iv:ZJuFI+EKp8EsAnrzmv5SAx17bJG+UYhXy7RW8OwO7Fw=,tag:6Urj1ypGBf62sJJH34V73w==,type:str]
            endpoint: ENC[AES256_GCM,data:86RNm0L459kbq3YtU7oxtXy0meNec/ClGuRnF/+0x20C33w=,iv:kWlMyU42OUwOT93Ecqzz5L4mkXXs0dzK2C9SR/CD0CM=,tag:hyUE7SGRknJGaNLukFGXSQ==,type:str]
            secretAccessKey: ENC[AES256_GCM,data:wAKXbkWDUFZVUIMM3EgUNzPZRDY9a3AU1hgYTUUcma6eF/CC/DTZEw==,iv:V8ng/MxjFJN2td8gPEcsAJQIs5pS5uIhEWUlPzZi7a0=,tag:8jA+KabYRsVzP0HvqX/BEw==,type:str]
            accessKeyId: ENC[AES256_GCM,data:f+FVHz/Hsk7RI5tBAM92bo6POQY=,iv:QRN7iHzautai9vsFK4Gtu1Tz3+rKqWxhyFp4ULUVP2g=,tag:SjL9Edps+g8hctdfiJZCQg==,type:str]
        bucketNames:
            chunks: ENC[AES256_GCM,data:+DVMl1ipkFkkTMUwr6Ra/XnCMx6Q4diyamvoD/8zaaSpjYuM4oN+63/aFtvmVbNGSiLhcA==,iv:xQundnWHaJz4B7QwMUllgU+0HJ6YNXBlyJjhc/UJgMw=,tag:5/AvXwt+b3lKqNOLB2Ca3Q==,type:str]
            ruler: ENC[AES256_GCM,data:X9JY/B7dvwOZDGQ2zsJn08DdkdT3szsAbR8bG1IR2nxqKMMAVXOQO1iRj3lOOOdxB9Md,iv:H9cAg+XetQD1m2o4+AaZU56avu2Zga/feo7bfK3Y20k=,tag:bIWY1fDAoWrxwKp+02Q/tw==,type:str]
            admin: ENC[AES256_GCM,data:gVqDkQOjTzVy2IcZibex/i7J0qOJAN4tF+Z2HfPBA77iNvHwqwGqlstYJvnoGd/cLTdE,iv:kCGFHFHLtArSiB0YiBc4YvEQBlDMMBxwwFLCletC1nQ=,tag:S4mqt2R+WnFWlOPnYQTX8Q==,type:str]
minio:
    enabled: ENC[AES256_GCM,data:AEr/Ew8=,iv:SvmMr7SR2ehQcABiwRvm9COnKG+JOU7QNaDoVn5ThUU=,tag:K9XCcNw9ZQGX4Ke8Q23T6w==,type:bool]
deploymentMode: ENC[AES256_GCM,data:uBDC9XCgGldx00id,iv:wDr0QbPFnNzNLDmZvKEDQOkQmgGrxxFJWVv15ADZASY=,tag:CotXKidt9T2HRzHnli4dcA==,type:str]
singleBinary:
    replicas: ENC[AES256_GCM,data:QA==,iv:KUUPUEO4Ry8IXXJGC03nIzzBdoftfNGkbyZffEdBI8Y=,tag:7FEW/V4UF2RDDn+n0Y7Gzg==,type:int]
#ENC[AES256_GCM,data:9bL9OyNuYro028tetg3D9FSMCSpBffZxeCAiz4a4XODu0/bhpeflpxqVt6XLrYVrXOg=,iv:8Iu9qCDIwptcJEDJAnwMyeWkQP5lhM0bJlYfN/tOmts=,tag:LxvIW+4ZWiVdAJH6j9yD7g==,type:comment]
backend:
    replicas: ENC[AES256_GCM,data:kw==,iv:Gvtlivg/1NGuuXYMfPzJO5M1zHbQ3elkLU3iChId1fM=,tag:io2Gay5lUKPqu3cposujPQ==,type:int]
read:
    replicas: ENC[AES256_GCM,data:Tg==,iv:AoQpxweCd1/l/QrwwdlE6FO3EXU9QlCyJbVsZMo/rV0=,tag:5hLQnhk2wFPiAwyqNEPehg==,type:int]
write:
    replicas: ENC[AES256_GCM,data:9w==,iv:bb5DRC+2fYUGv4Ta+huyu9bk4VKJ1xS0LkdqRrCRv9A=,tag:O3+4K/FJqFXvXWXXQ1u6Tw==,type:int]
ingester:
    replicas: ENC[AES256_GCM,data:KQ==,iv:32aDYOi0c1xbWGsq1zrfpuwdI/5wHAFTO8Ukp5tqe/0=,tag:Iiwz4zsc8I/tDpf77gwHAA==,type:int]
querier:
    replicas: ENC[AES256_GCM,data:ng==,iv:zqtsooNpOoND6D09xSm3nXMFN6Bc54dYtmSB6GbNGkw=,tag:rHo1qV/J/L7FG/3GZErH7g==,type:int]
queryFrontend:
    replicas: ENC[AES256_GCM,data:Ig==,iv:TN+YykL5jZ9g+OWO1bS2cbEFceEBhwZZz8TtXcJ69so=,tag:NvtXJtyDYFvf1z2dXtDonA==,type:int]
queryScheduler:
    replicas: ENC[AES256_GCM,data:ZA==,iv:Iv6lFHDwhmUZgEk4ofjWgOknjW2lo4hAyoKIw/677Vo=,tag:P7JGjfJxTle9bSde9wGQlg==,type:int]
distributor:
    replicas: ENC[AES256_GCM,data:jQ==,iv:4btZtPTUVKckKS5adA8lW4DzG2ig/vfTJdYHfLqmxlE=,tag:l4/2gPVe2aU3LoiFjOIkLQ==,type:int]
compactor:
    replicas: ENC[AES256_GCM,data:Xw==,iv:u2Dv5AOPnJ0dTO50QO2VFullNo6IAhHHy4368Jff9Cg=,tag:ypIxBFLADY9+k1CsGzUiMw==,type:int]
indexGateway:
    replicas: ENC[AES256_GCM,data:vg==,iv:+GCCzrHgbOfOldtcIZkJE6tZzhGshOYsBVe6ZaCnQPA=,tag:zJfS7un0u7QgnWNh0LJzUQ==,type:int]
bloomCompactor:
    replicas: ENC[AES256_GCM,data:Vg==,iv:ElR8cWLggE/rzKLFuQD1dxwyilOVFT7F0ZgDsbK3aLc=,tag:eU4mwZZkUMn/zbFLARZk2w==,type:int]
bloomGateway:
    replicas: ENC[AES256_GCM,data:qA==,iv:MDhQTHtpAidGTPwzpjjNPBXdYnhuUT68iGHKK9X1Ejs=,tag:R8WJ7sIAlACp2HtJ73W1Iw==,type:int]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-07-18T01:05:00Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgFixJz/5tVWC/b8oQAP1KS7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMbG1F2J91rHFE+q85AgEQgDuqiwAH86BGUug1EkzA3Iv19BG7I8EDY2kK5sb0H8t21Y/Kg7FoeT+jtyyLRcfVC97lex9E+8UsmBHNJg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaDFCYkZFdFpucWE0Rlhn
            UTFpaDhBeURuSG9WN1lXS1JUc3hRelZ6ZGlvCjBRSjJVci9tdWF4Qmg1N2lwK1Ux
            SldyQXNkV1FwWUtzZUdYYWZ2YmxPUk0KLS0tIC8xYVloSEEyWlFHdzR5TW9kaDBQ
            Y2cyczdTYnlJY3I0U0dIZ2JVMnNaWlEKr0ZRKDn1I+xxBfqVPMkpifoJXMV7eHEe
            37aW+FHBqiefaQUUZ+0qZ+TIZOIWw6H92WShLJIzwnrbEXZLoKXPug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T01:05:00Z"
    mac: ENC[AES256_GCM,data:DloNGknVQ1vAB/Fzwc7USCQlBQwWZEwR93+3zPuoTRt58/llARUsbYBElpjSqBb3fGh80DfSkKWb+PCv5VL2DE4Jni6ta1XggxIGfJ9QNKYweRKSZbkn8dArgrq+wjrYnafV2tIuSzAqF+qSWz/ItZOtGKOuoMrcnV8XHTh2sFY=,iv:rMcMAxZEM6FACl+eVZ/Tpdc/7A6uYKQlR4XC5evu5hA=,tag:4eotokypZXmLTPQC6Y1CVA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
