alloy:
    mounts:
        varlog: ENC[AES256_GCM,data:uVV7Fw==,iv:ak/qvodX66glQfMfpWZSeyRXa7nEc6YdhlmIcfEjEDY=,tag:tOyv+b6xcDeZNgCWVKOHBQ==,type:bool]
    configMap:
        content: ENC[AES256_GCM,data:pLGXLnJm40hlKVwXqIiUQSsGcQQ92V51QsgkjKssI5dG+fR6i1tJM7eRBGNgAha7P1it6IwiuQx92+U+85lB36lmv1qxEFT6d/e8jJ5jRb6nY56RPzHroysIbfiBLaZ0cUnC80zqxdvXPSUrjkCeiB0ExyI+HLJ/iIoD5SJX4bi/Wxzkg2sET//IQqoVvHZIq1feva9+DPmyGNAc9dIHYdK0tUWfXioTUXRUKZH0fdZhdSqk+5wb8udtLrPDTit44QxyYFL3c9PISGfNaFJHbDCl+KeSClwjHF6PeIs61GxczBGial/fVid5NX90bSN4YaJXFk5koxKrouwnmQqsfHeHUQEnPYTcoy77BHFZAyXOx5KtfW3HMHL5tXQmywTnyIO37bFZcLWMq+Xfv/kTSAuhg/aJa2H8KuSwCij5dez1csqSGK3twWAY2D7SPf5bJXLF98wl3e7DbYRW+d8frvDOOfY=,iv:iXUgUx+Ogn/NWQLuMP3iSkqYt6LU18dIZ2Zyx+xlGXg=,tag:fDlrOZD945YaiK/mfvaD2g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-05-19T03:41:44Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgEN+bBUkbi/iot3+RRdGNr8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMX4JAkM1kOsoBr35YAgEQgDvrnLkqRpG+I/2s5NlIz+4nmUXDhKJwfkCnH5R4rxD4PePF72JzDHKnVm0IVUgEOT5+JFdjCf8N0NDeiw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TTAvQ3c4NC9oa0VZVkFl
            Ym16ZVZQNkN6c3ZwR3ZXUnFmNXM2Mis4YUU0CkprMUNpOWZhNERwSnptd1hraTlH
            YVB1MlA2Z2VDNVpVUGNkV1Nwbi94bXMKLS0tIGVTZEloSUJHWTVwUzZlZ0hmNnhj
            dFArNVI5ZnllS2hXUGFNVWVJcFF4Z28KpOT6K1nwSvZcppsflcja1xfgdebR0W40
            MPs85T9OVHJmhvmp7bz9Pn7k3uPeDo7ovm+BFG3qTj14YtHdslncgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T03:41:44Z"
    mac: ENC[AES256_GCM,data:dlBJXcRWIijlfnsKpnCImthWb5c5KvZo2kcsGHBu7yiOc+/2MVbtQf5JZUT5uCC2iBmc/NOsPpdkiOdrNVUs1+WwoNOhWegoYVAxsND2vlxHJTMVQ7+NzOchAxtGWOkX8vvTIeX0Z1/0Sov54Ia4uJEV3ZXzNogBOHEg133jN3A=,iv:nAB5lD6iAcNWjFWrYZ1jdFojH1YTNQd9aFrtUXeeI0U=,tag:zmgP2p6qr0dqWZOB4Z450w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
