apiVersion: ENC[AES256_GCM,data:sZs=,iv:6gwSLbuY9Sm8TCcD8YcOn0oD4U4DpDszXGA2zyg3CXc=,tag:QbKQpdukbGhqngwHjkSP4g==,type:str]
kind: ENC[AES256_GCM,data:6e53VJRd,iv:H4I+QW6yo0jwMvF+7WZv/N5GCenLKGTDUrNn1QIADKE=,tag:fzhjzxo4N0PWBpJ2yghCag==,type:str]
metadata:
    name: ENC[AES256_GCM,data:a0EZ9jk+,iv:VZ+7KxZnL4hgmYEwTN8y2Xg0Jgka7ldXBfFlqLtFIkk=,tag:EaKbZh2BiU7Gsqyrh2zleQ==,type:str]
    namespace: ENC[AES256_GCM,data:FEIVeE34RO3bfg==,iv:bCu3eEFCZh7QxSJlazHkj4UDm39nv1XEe7YXdigWxwo=,tag:ZvvFt00+UK1HUSkXR8Dz3Q==,type:str]
type: ENC[AES256_GCM,data:0OYz6fzR,iv:vJCZqcK0YB8dWMwxNxyW1/M7D3zH/B3ErFn6jJDgTcQ=,tag:OxsB4esd1CwOqLeDe5DZ7A==,type:str]
stringData:
    #ENC[AES256_GCM,data:+fodo+Pts7MLDwQuvzJSyWumzb663en6UcYt8m9fPwfnRES6QC3yG3QAjWxya8Q5uANHFyzpwp2Hr9RMFF5T0+4YedigpU05lVFtd5XK3cR2lM8krwuuZC/CTlzOAaJmJweztTcwW/hobEv32ovc7HY=,iv:GwOMOtVHeUJ0JN5NCcPaVeXTf5tDS0xL/MlZckRSK1g=,tag:rsEvm/RgmF39g+SCGLBXvw==,type:comment]
    GF_AUTH_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:UCPgMWOGPjMVJe/okmUlIHnesmc=,iv:CLkmNZihalp4OsqpezbDIYbDDvTph0ZYGvnQtFYwM9k=,tag:M3bMsdbJY3ak+Rf0884RtQ==,type:str]
    GF_AUTH_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:1y+qYZSBvBH9jHxuCaAYFSJNxuazl6bo3laZe5ImjMsOrtvAAq9tGg==,iv:8PZa3ww2ZsiTFjWMagoVWapU8sBOSEGE6ymzQu5knAI=,tag:fcOUfiqLSfEs9ikfYR8Rmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbVpDR3VXbXVDYTBlVVNp
            Wlk5TzcyMDBqTDNuSUZ0T1NIOXZwdFBNU2tZCmNoYVZ2ZnhzTnFidTlKc21ZZUpW
            ZUhXb00wUktVRE1DeEp1RVJiQ0ZoMTgKLS0tIGQ2aVI1MVd6V0dBUHo1R3QxL2xw
            OUFYRUtTcmE5VFUvWmlNVDEySkVpaEEKX/ILlnXOMQ7y4NMro9s5taHr8ultApqP
            zqDwlQLUAgbVxvRBNLYEaZ0NbnGdh4Rw0ESDHVSip2wq5lPlKlTTuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:04:00Z"
    mac: ENC[AES256_GCM,data:pQ3Bk8nulpLrmh5DwiyJWOzHcpHxcT8s3SLeQUo8EREjALqSKpdW6PLmrF9rYC+DLDwFmiqLQaU8eItvRS+P8DTk4NyRLuu/tI9QA0v5+PwuACNCBhttVnlakefgdFB0qKp8rrP+skm+FmJ6p2CiwrAako+NFkCXFjzz6uStxg4=,iv:dI68yCZpQCVkOTZLkcfysiNmrQbGj3UPzofYmT2Mbwc=,tag:XDz5jFSRs3yCOz8d2s6a8A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
