apiVersion: v1
kind: Secret
metadata:
    name: dex-auth
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:srCUQri63rSmm1vv0ejVwNG4ZlB6uDCod5AOeeMrgvR5UvICPPG4tZ1WxoHoHpY+dtJ2L6tMiF1ucIKz69SO+pGSPJb00Dllob7Rp3KWAMzeSyhX31kM4O/vu8xINAsrovcKLg==,iv:BKCByPc0IR4RfnCYcVAclZJJbimc8BIA2nHCz+5+Mws=,tag:PwUhk/n+O/dyFV15v750oA==,type:comment]
    #ENC[AES256_GCM,data:nxJTGlB8iBr1TLGB3TDLiSKcS9C7ggiw2MPXETmUKVKKa5Dnz5bCgTxOUqqgRQd/WMMU/byYDJkag9WuJ0ZerurlM0gxNLEG7m8=,iv:0Fuq7ACdvrA2MKhGI8KtscaiYMkHhZGe+3NbLLYaZRk=,tag:gqtMzxYN01VepcA/hps3MQ==,type:comment]
    GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:nYt+Oi5GEPEE/faf1fXEqdQjRBpH49dMGLvY83k2IKw=,iv:FJWxkqF6kke7bHl3ok6QsmrmxwwUBaUFjcZHtaw6hP8=,tag:QOT4t6Y4pJrC3UYnPwpe/A==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:vKONLMqH9rIS9bvRgy9UK0ncgAh0ahc4Ya/gOugVF84dtTeP6Zt8rujkDSi+Tq0Z/IZS4E7GddAwDU6T1OpxLIbVqFSNm3I+CCsoy9mBuN0mcSbYhrjarjmIIwRWh/ii/OoCB8ttGjYsACJ/KruSlpfEWZlZCDTgXQ==,iv:ZDNQTvZMmE+IxQaNuZR/4DrVSE7UHsOskUOUE9yuf0A=,tag:lM6wTqQSaHr5Hu0aT8fEOw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-09-13T23:09:17Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgH3TyIrKybK4JyLE/+UYZr9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzYOfFcjCvENFKl/DAgEQgDt6ydEgGF0GhXvag3HUztyxhFcFUZrSB7+chCzqoY/FGmSimsKh7qqNN2WTX0PYk5N8yLEZiBMeXeiiuQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdEliRmJFb0FJRUJ6UlhU
            MXA0eU40eVhnV2ZGYmtYZUVKNlVaeUZTSHlJCm1jeHl5WGFLUkhKK2Jlc2h2Z3R4
            KzdHakVwYUVXU09iVVV3RWZoNDBnRHcKLS0tIE5QcHM0eHZ3Q1hNRHkxTjBQTkpn
            L0V3bzRydlNFcWIxS1ZjNldWK0R5RlkKaA4MngNTstuft//bzKrqu9WCTS8KGtCh
            4DXDDyULwZUeDNHb5Ja8YJepBo5Q9AMs3UHgUl9mqzwL+xpnRDnfFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T23:09:18Z"
    mac: ENC[AES256_GCM,data:9VXqCecF8k02VA5jqF00Q39+OAFLomLpHOVGOn90G+7NQPGQ+ibaNzhh2efHSd4ZCkbQRxewXEnwz29GGThWvoi49II2QguvalsgqBzRSLqsjT1uZO24O7cpy6gmVrR4iMBJctCTc8I9RNBFtngCqkbW4FQ2FEzUzcFMnPmcrVg=,iv:vz7Wxe4hiQMMDUAspDBNjBiw+NPUCy/1kK3YMXsZJdo=,tag:trUTEM8LoYEBXNajMu/BHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: loki-s3
    namespace: monitoring
type: Opaque
stringData:
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rxEjuB7D+smmz13pubOqYr9+aAhtIXZfUQ+88t5A/lvl4jjFj8lCqg==,iv:U9jpe3kZf25wLk0R/mE/eS/OmwnlDGx82k3yEaI04K4=,tag:RnY89RAusldlbK2lhPN34A==,type:str]
    ACCESS_KEY_ID: ENC[AES256_GCM,data:pbutj4Rq+xZ6ObbB+ntgIpCBNsc=,iv:LevEfJ7TQERH6no+d/XlIa8OgM2T7Xixp3FEZOa029k=,tag:jM7gtzQb0N9NS2z9dJAJrQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-09-13T23:09:17Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgH3TyIrKybK4JyLE/+UYZr9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzYOfFcjCvENFKl/DAgEQgDt6ydEgGF0GhXvag3HUztyxhFcFUZrSB7+chCzqoY/FGmSimsKh7qqNN2WTX0PYk5N8yLEZiBMeXeiiuQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdEliRmJFb0FJRUJ6UlhU
            MXA0eU40eVhnV2ZGYmtYZUVKNlVaeUZTSHlJCm1jeHl5WGFLUkhKK2Jlc2h2Z3R4
            KzdHakVwYUVXU09iVVV3RWZoNDBnRHcKLS0tIE5QcHM0eHZ3Q1hNRHkxTjBQTkpn
            L0V3bzRydlNFcWIxS1ZjNldWK0R5RlkKaA4MngNTstuft//bzKrqu9WCTS8KGtCh
            4DXDDyULwZUeDNHb5Ja8YJepBo5Q9AMs3UHgUl9mqzwL+xpnRDnfFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T23:09:18Z"
    mac: ENC[AES256_GCM,data:9VXqCecF8k02VA5jqF00Q39+OAFLomLpHOVGOn90G+7NQPGQ+ibaNzhh2efHSd4ZCkbQRxewXEnwz29GGThWvoi49II2QguvalsgqBzRSLqsjT1uZO24O7cpy6gmVrR4iMBJctCTc8I9RNBFtngCqkbW4FQ2FEzUzcFMnPmcrVg=,iv:vz7Wxe4hiQMMDUAspDBNjBiw+NPUCy/1kK3YMXsZJdo=,tag:trUTEM8LoYEBXNajMu/BHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: loki-basic-auth
    namespace: monitoring
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:o6ScOc8khOzntr1jLJ113j5HxXj0MbQBcAoeHJFwu6RNVHCb4hVRiUWfA/4S/BQ=,iv:29vZcb0qXWCUqWwjtBqeTBp3+YL/84FaZIuGcYF2xxg=,tag:wgbDyq2p+cdr+VYGo9IpVQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-09-13T23:09:17Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgH3TyIrKybK4JyLE/+UYZr9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzYOfFcjCvENFKl/DAgEQgDt6ydEgGF0GhXvag3HUztyxhFcFUZrSB7+chCzqoY/FGmSimsKh7qqNN2WTX0PYk5N8yLEZiBMeXeiiuQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdEliRmJFb0FJRUJ6UlhU
            MXA0eU40eVhnV2ZGYmtYZUVKNlVaeUZTSHlJCm1jeHl5WGFLUkhKK2Jlc2h2Z3R4
            KzdHakVwYUVXU09iVVV3RWZoNDBnRHcKLS0tIE5QcHM0eHZ3Q1hNRHkxTjBQTkpn
            L0V3bzRydlNFcWIxS1ZjNldWK0R5RlkKaA4MngNTstuft//bzKrqu9WCTS8KGtCh
            4DXDDyULwZUeDNHb5Ja8YJepBo5Q9AMs3UHgUl9mqzwL+xpnRDnfFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-13T23:09:18Z"
    mac: ENC[AES256_GCM,data:9VXqCecF8k02VA5jqF00Q39+OAFLomLpHOVGOn90G+7NQPGQ+ibaNzhh2efHSd4ZCkbQRxewXEnwz29GGThWvoi49II2QguvalsgqBzRSLqsjT1uZO24O7cpy6gmVrR4iMBJctCTc8I9RNBFtngCqkbW4FQ2FEzUzcFMnPmcrVg=,iv:vz7Wxe4hiQMMDUAspDBNjBiw+NPUCy/1kK3YMXsZJdo=,tag:trUTEM8LoYEBXNajMu/BHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
