apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin
    namespace: pihole
type: Opaque
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:UdB9QhuJQzHm5w==,iv:zWgBLaxG0s+HsVXMdhWP24fGaIbzbm7V9TENvbFjALQ=,tag:7PvbMVRowoIgYkuEZdZ1zA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-07-02T05:30:25Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgGT2dciTBALsKOvHQAzzV3bAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQGwktFfgaK54s9sJAgEQgDs4vnYoeIYixk9P2oHLYgZMbC93/fz8HNiUYjUsoLDSQZcpBsjy+tO98mlXzWuDf1/1D7xYG98diQb0tA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSGVIMlhFRDdnM2hwN2RT
            SmxPZ0xWeFN1S1ZRQU92dFpuWVppV29KaVhjCnJtaFZIUGh2c0l3V013WFQyWjZv
            MW1hTmFlcE9sanNGZUZFSnZvc1VSaFUKLS0tIE5IZ3YwY0IzR1NaMytTNUdjVnU1
            dEJWYzJvUnZnKzl2TTFwSSt3c1hYU2sK0FH3k3+qugI4eIkXbvO8FxeVEsVGMZC8
            GqrVdJGkjlZ+vdLg3dJIQhejCdFxPU2Zf5VQxsurHBLKPyXAtbiXsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T05:30:25Z"
    mac: ENC[AES256_GCM,data:FtaGRdMMJaN2kfHXE3DyqWUz4CQpuYWMbIN+ZzShaaCSvgG3IMoLzBTCUQyfrYAwr2JPcjXdAHmouPLNRkxu4gnzI9Po1ceS9iSZUHUw5jdkL9FxLzErhMULbavhAE+5oFKAw6unw3S2L/wtVHOfXRKQF9ptwlkT8ItujESMJB4=,iv:QXXaEr5+Qg0ZFuApRYY9PbH2+L+pdnG0ZXoS4ZbHCWQ=,tag:AIAcl2pE2m9yk2IWxFZkTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
