apiVersion: ENC[AES256_GCM,data:rNw=,iv:8+f19K/V9o74y/YaxF2HqN4WUwqefjP/8hwMw6CCTJ8=,tag:5Wi365FyLklojKOGDI/IpA==,type:str]
kind: ENC[AES256_GCM,data:1XRaIhRB,iv:ME89WEf4zcObuGIsKxZrNRdqwPLu7xHMGy7E7m4fu5Q=,tag:8Pba0xz1TEkA1pvL5TgPbw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gzQWPJp7p/hlRU9T9Gk=,iv:3ZeINa1nHL1zoCa4m6Ba9E3OmyKvnPBH2FWCCgk96QY=,tag:Wq/viqq3jOcB7Y5k+8qoXg==,type:str]
    namespace: ENC[AES256_GCM,data:4Pr8NMYx7GE=,iv:ItbFr7Sx6TELSxsRJk3J0poH56kwirkvLe4BTT22zbw=,tag:6Wrs7lz31I4atMxAAjWegQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:2Pj1CrD5X1h27okCLS+HoGvZJQ==,iv:SXAOrmZUJz1CArYz+x7PsNZ1Fft3tFfX47wXxMNWz0o=,tag:pWA6RdyfLh5VFhepnFJQcA==,type:str]
    password: ENC[AES256_GCM,data:EhO0N4gBLdJmyMt0atfErA==,iv:RVPf0eeRyLkgtQlnPsYliBbkFUhkSBw2eMoDkt+cnb0=,tag:NkEBomqmyznA6Z68jQOQWQ==,type:str]
    #ENC[AES256_GCM,data:HCXYGa2g5HgKvd8hqh59S2EJmPeCqZKX4M1Pj8EhswAbsNwDETW36BmGsvE3WTCwia/+m2rRKMilFhuGZZpiwASlPm27,iv:jJNJDaKV+dTu5I9UBRsOe/YItfQvtWsEr+OS3mU6VeA=,tag:L4vePD2esXZqMFUt/bVY8w==,type:comment]
    dns-api-key: ENC[AES256_GCM,data:ijWgjRpbGYm9IHpwCcxAjTasaZH302PsRVL7Z0gcJEx9XXvkVnWmgA==,iv:Mysn1p2ny1JnwogFAmnO6MFRS1Ot0cJqh+Uv2fzTGY4=,tag:TPwZlNMU/z2wERsYpwLjdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VnZxQU4wdWx6Q3BqVUQ2
            NjRrbW01YmdEZWQ5WTYrV1lSZ0ZKczVHRW1rCjc1ZjdhWUtsUkUrbUdBNlV0REhR
            bTBkWkRiWkZEQ2M2SE9ZTlMwb1lmZUkKLS0tIGVVRk1iNG04SG5TTTg2MkxhYXVh
            WTgrNjN0eE1YRHJaUXc2ekcveGk1VWsKNrU6dPu/Ij08Ar5fGJzLrE9rh35dvE3P
            ATX2DTj1ngIGp5iwQOBkJEDnuJQyeATQsd2bLAWKfFppWMVYL8DI+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T04:19:56Z"
    mac: ENC[AES256_GCM,data:ouCuhH25Y8nNAhVFOnEhvALuPJrJa0KdNnCpT+1vFdJ3JdDqoEEWC05YCNVpak/NLvvKAp02b8y+UhaDHnGzJAxJORL3YOt0UtEui7fyfqAgKpLUAraOMEn7RYWJsYQLwa7ByBqfJEE/1VtneCI4UFVI8ck0IRDnRdhbOdklEzA=,iv:GUvS3TLnOm+QustfjV14Wzb7R/g3E2LjL/2lPCW5ZnI=,tag:s3/rdlrSyUzfyD4tPbtw3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
