apiVersion: v1
kind: Secret
metadata:
    name: stalwart-admin
    namespace: stalwart
stringData:
    username: ENC[AES256_GCM,data:pEVK1yQN8WT2scBoQML+9EDdSA==,iv:wOAXCFFqdeNKilMsL/wKLcceqqiqTfS3v0ALFIckJMs=,tag:Awxt8eXccjyunCd2TSUGEg==,type:str]
    password: ENC[AES256_GCM,data:rASY/4FWd8hQSZQzN+Dl7Q==,iv:qtwO1hr9TdXTZV72rSufGppKz2N9PSL6dAbS5nDHpAA=,tag:cGYAlSpKr6469bZ0a/CUxA==,type:str]
    #ENC[AES256_GCM,data:YVtV1+II19w2r9CjjuARwJnIQwp86IfAkKpHiTySbTyvMRCmLLvkDhKScm3wp4Ct20lLB+W2y/7WRN6mrDrBBtBwx3OM,iv:kg0fhwHMUPHWeP61K2oYxnV97uDUw2WQxexl3FRvKAg=,tag:P0nyJnwdU2Q94ya810Rg+w==,type:comment]
    dns-api-key: ENC[AES256_GCM,data:2xdloC2Q946Alf46sxgWmPTNyAESQapprs657cRVi9lmvASzh9Btjg==,iv:A38HbFpZ9vDANSRd5BuU2GQrHu8BGYVtRNo4E2l7Ku0=,tag:QezFuvLVZug42LXwy3Jvbw==,type:str]
    resend-api-key: ENC[AES256_GCM,data:fERBvR5zFYhI5ueIHk+nY3r75YS/rTgSvKCsAymoKP9GfvAx,iv:7MbDi+G2FJPkxbRvkCBamnDmU7QmURMO5+3onRe+Rys=,tag:/GPS6Zr6loyLwVKlwOwa/A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-1:061349021976:key/aa320f6e-8677-4b20-ba4a-a397b9b6ef4f
          created_at: "2026-10-06T21:27:31Z"
          enc: AQICAHgs6Vc7psOJ5zsR5mf8eWfzoQ3QNJYc83uk6RP4fu4nxgEUp6T3jGCzD0F64+lIIJ91AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzkcACjieVijurj+MAgEQgDvX5XOdKe62249W4rtvnZL/zMhvDaQBupSekY0O9BV/0eAn3HHig9qwJHnOkEIA4yuWAfsjkPqVc1LGRg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zafe3axpkvz9y8uv9d82mqr4e92yx5dhvuu5jsc4y0dzz97wlu4qt5uxqz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQkJ2QXRyMDBMVFhuanpx
            aXErdE5GUTJFSDZTaGh1bmc5VTBBTG4zQjBrCndldFFYQ1lIWVNkeWdWRVFzRVE3
            MUZLQXAvcUo4akNpb0tkY1Z2OGJFWUkKLS0tIGs4K3ZzUTltMFFRV3dhMXhQVmxS
            NnU0UFI4bG1aczhaZDV1ZUNBL1RTS2sKdbYll5t2Zi2WLhc3qm06njhzLpYV687M
            taEKd/Bdy+0GzB/IMScfqdFg5vWueVHE8BtghEKI99HhE7JlURpEtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-06T21:27:32Z"
    mac: ENC[AES256_GCM,data:sMitn9Q/jW8m8fDmkkILrq/Q4R9ZeP1IGhcUxFDQpUdMaCZaza+y11hVP4omFcC6whAojBTifeobLR488IH8HqBolAyjMR2Qf/1SDTxcQrgPCes52KP4+YHOl215THh/8J0jK/x4OC3eGhN9zaVur+RYz4UTtp694VbWVJGfyso=,iv:c4gVetudRz3UDAvju4UUEcii78bk+QBzdeeygW1VsUw=,tag:9EiaxKXOVgk6JI8LlXvTEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
