apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: games-project
  namespace: argocd
spec:
  description: Games Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: enshrouded
      server: in-cluster
    - namespace: satisfactory
      server: in-cluster
    - namespace: soba
      server: in-cluster
    - namespace: valheim
      server: in-cluster
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
  roles:
    - name: read-only
      description: Read-only privileges to my-project
      policies:
        - p, proj:my-project:read-only, applications, get, my-project/*, allow
#      groups:
#        - foundry-oidc-group
